#! /usr/bin/env bash

set -eux

while getopts "c:" opt; do
    case $opt in
        c ) camera=$OPTARG
	esac
done
if ! [[ -v camera ]]; then
    echo "[ERROR] No camera" >&2
    exit 1
fi
shift $(expr $OPTIND - 1 )

search_dir=$1

function find_photofile_with_matching_photonumber() {
    local -r searchdir=$1
    local -r photonumber=$2

    local -r maybe_matches=$(find "$searchdir" -type f -iname "*$photonumber.jpg" -printf "%f\n")
    
    if [[ -z $maybe_matches ]]; then
        echo "[WARN] No matches found for photonumber $photonumber from $file" >&2
    elif (( $(wc -l <<<$maybe_matches) > 1 )); then
        echo "[WARN] Found more than one match for photonumber $photonumber from $file: $maybe_matches" >&2
    else 
        echo "$maybe_matches"
    fi
}


find "$search_dir" -type f | while read -r file; do

    extension=${file##*.}
    
    if ! [[ $extension == "jpg" ]]; then
        continue
    fi

    case $camera in
        s70 ) exifFilenumberKey="Exif.Canon.FileNumber";;
    esac

    filenumber=$(exiv2 -Pt -K "$exifFilenumberKey" "$file")
    if [[ -z $filenumber ]]; then
        echo "[WARN] No filenumber in $file" >&2
        continue
    fi

    # build photonumber from filenumber
    case $camera in
        s70 ) photonumber=${filenumber//-};;
    esac

    search_for_match_in=$(dirname "$(dirname "$file")")
    matched_file=$(find_photofile_with_matching_photonumber "$search_for_match_in" "$photonumber")
    test -z "$matched_file" && continue

    matched_file_extension=${matched_file##*.}
    matched_file_basename=${matched_file%.$matched_file_extension}

    file_basename=${file%*.$extension}
    variant=${file_basename##*-}

    editdir=$(dirname "$file")

    # TODO move to converted!
    echo "mv $file $editdir/$matched_file_basename-$variant.$extension" >&2

    # if xcf exists as sibling of jpg file, rename that, too
    xcffile="$editdir/$(basename -s ".jpg" "$file").xcf"
    if [[ -e $xcffile ]]; then
        # TODO move to converted!
        echo "mv $xcffile $editdir/$matched_file_basename-$variant.xcf" >&2
    fi

done
