#! /usr/bin/env bash

set -eux

while getopts "c:" opt; do
    case $opt in
        c ) camera=$OPTARG
	esac
done
if ! [[ -v camera ]]; then
    echo "[ERROR] No camera" >&2
    exit 1
fi
shift $(expr $OPTIND - 1 )

search_dir=$1

find "$search_dir" -type f | while read -r file; do

    extension=${file##*.}
    
    if ! [[ $extension == "jpg" ]]; then
        continue
    fi

    case $camera in
        s70 ) exifFilenumberKey="Exif.Canon.FileNumber";;
    esac

    filenumber=$(exiv2 -Pt -K "$exifFilenumberKey" "$file")
    if [[ -z $filenumber ]]; then
        echo "[WARN] No filenumber in $file" >&2
        continue
    fi

    # build photonumber from filenumber
    case $camera in
        s70 ) photonumber=${filenumber//-};;
    esac

    # search in parent dir for matches (if more than one continue)
    maybe_matches=$(find "$(dirname "$(dirname "$file")")" -type f -iname "*$photonumber.jpg" -printf "%f\n")
    if [[ -z $maybe_matches ]]; then
        echo "[WARN] No matches found for photonumber $photonumber from $file" >&2
        continue
    elif (( $(wc -l <<<$maybe_matches) > 1 )); then
        echo "[WARN] Found more than one match for photonumber $photonumber from $file: $maybe_matches" >&2
        continue
    fi

    matched_file_extension=${maybe_matches##*.}
    matched_file_basename=${maybe_matches%.$matched_file_extension}

    file_basename=${file%*.$extension}
    variant=${file_basename##*-}

    editdir=$(dirname "$file")

    # TODO move to converted!
    # FIXME this will drop the variant info
    echo "mv $file $editdir/$matched_file_basename-$variant.$extension" >&2

    # if xcf exists as sibling of jpg file, rename that, too
    xcffile="$editdir/$(basename -s ".jpg" "$file").xcf"
    if [[ -e $xcffile ]]; then
        # TODO move to converted!
        # FIXME this will drop the variant info
        echo "mv $xcffile $editdir/$match_filebasename-$variant.xcf" >&2
    fi

done
