#! /usr/bin/env bash

set -eu

declare -r NO_TEMPLATES_DIR_RC=101
declare -r TEMPLATES_DIR_INVALID=102

declare -r BASEDIR="$(dirname "$(readlink -e "$0")")/../.."

source "$BASEDIR/lib/strings.sh"
source "$BASEDIR/lib/photofiles.sh"
source "$BASEDIR/lib/iptc.sh"
source "$BASEDIR/lib/exif.sh"
source "$BASEDIR/rawtherapee/lib/sidecar.sh"

while getopts "c:k:d:t:ov" opt; do
    case $opt in
        c ) 
			declare -r CREATOR=$OPTARG;;   
		k ) 
			# CSV string, using ";". no quoting needed for keywords with blanks
			declare -r KEYWORDS=$OPTARG;;
		d )
			declare -r DESCRIPTION=$OPTARG;;
		o ) 
			# old keywords will be kept
			declare -r OVERWRITE_EXISTING=;;
		v )
			declare -r VERBOSE=;;
		t )
			declare -r SIDECAR_TARGET_DIR=$OPTARG;;
	esac
done
shift $(expr $OPTIND - 1 )

declare -r TEMPLATES_DIR=$(readlink -e "$1")
if [[ -z $TEMPLATES_DIR ]]; then	
	echo "[ERROR] Templates directory does not exist" >&2
	exit $NO_TEMPLATES_DIR_RC
elif ! [[ -d $TEMPLATES_DIR ]]; then
	echo "[ERROR] Templates directory (first parameter) is not a directory" >&2
	exit $TEMPLATES_DIR_INVALID
fi
shift 1

declare -r PHOTO_FILES=$@

select_template() {
	declare -r filetype=$1
	declare -r camera=$2
	declare -r lens=$3

	if [[ -e "$TEMPLATES_DIR/$camera/$lens${lens:+/}template.$filetype.pp3" ]]; then
		echo "$TEMPLATES_DIR/$camera/$lens${lens:+/}/template.$filetype.pp3"
	elif [[ -e "$TEMPLATES_DIR/$camera${camera:+/}/template.$filetype.pp3" ]]; then
		echo "$TEMPLATES_DIR/$camera${camera:+/}/template.$filetype.pp3"
	elif [[ -e "$TEMPLATES_DIR/template.pp3" ]]; then
		echo "$TEMPLATES_DIR/template.pp3"
	fi
}

set_iptc_creator_copyright() {
	local -r sidecar_file=$1
	local -r creator=$2
	local -r photo_file=$3

	sidecar_set_property "$sidecar_file" "IPTC" "Creator" "$creator" 

	local year_from_exif=$(exiv2 -Pt -g 'Exif.Photo.DateTimeOriginal' "$photo_file" 2> /dev/null | cut -d':' -f 1)
	sidecar_set_property "$sidecar_file" "IPTC" "Copyright" "Copyright (c) $creator $year_from_exif"
}

function sidecar_targetdir() {
	local -r photofile=$1
	if  [[ -v SIDECAR_TARGET_DIR ]]; then
		echo "$SIDECAR_TARGET_DIR/$(basename "$photofile").pp3"
	else 
		echo "$photofile.pp3"
	fi
}

for photofile in $PHOTO_FILES; do

	photofile=$(readlink -e "$photofile")
	! test -z "$photofile" || continue

	is_original_photofile $photofile || continue
	
	sidecar_file=$(sidecar_targetdir "$photofile")

	if [[ -e $sidecar_file ]] && ! [[ -v OVERWRITE_EXISTING ]]; then
		test -v VERBOSE && echo "[SKIP] Sidecar $sidecar_file exists" >&2
		continue
	fi

	if [[ -e $sidecar_file ]]; then
		old_keywords=$(sed -rn '/\[IPTC\]/,/^$/ s/Keywords=(.+)+$/\1/p' "$sidecar_file")	
		old_creator=$(sed -rn '/\[IPTC\]/,/^$/ s/Creator=(.+)+$/\1/p' "$sidecar_file")	
	else
		old_keywords=
		old_creator=
	fi

	test -v VERBOSE && echo "[PHOTO] $photofile" >&2

	camera_from_exif=$(lookup_camera_from_exif $photofile)
	if [[ -z $camera_from_exif ]]; then
		echo "[ERROR] No camera info found in EXIF data of $photofile" >&2
		continue
	fi

	lens_from_exif=$(lookup_lens_from_exif "$photofile")
	manufacturer_from_exif=$(lookup_manufacturer_from_exif "$photofile")

	test -v VERBOSE && echo "[CAMERA] $camera_from_exif" >&2
	test -v VERBOSE && echo "[MANUFACTURER] $manufacturer_from_exif" >&2
	test -v VERBOSE && test -n "$lens_from_exif" && echo "[LENS] $lens_from_exif" >&2

	file_type=$(echo ${photofile##*.} | tr '[:upper:]' '[:lower:]')
 	sidecar_template=$(select_template "$file_type" "$camera_from_exif" "$lens_from_exif")
	if [[ -z $sidecar_template ]]; then
		echo "[ERROR] No sidecar template found for $photofile" >&2
		continue
	fi
	test -v VERBOSE && echo "[INFO] Using template $sidecar_template" >&2

 	cp -f "$sidecar_template" "$sidecar_file"

	# if we have a creator from an existing sidecar, set this in the new sidecar, too. so to keep
	# an old creator, just call without -c option.
	if [[ -v old_creator ]] && [[ -n $old_creator ]]; then
		set_iptc_creator_copyright "$sidecar_file" "$old_creator" "$photofile"
	fi

	if [[ -v CREATOR ]]; then
		# TODO add new iptc copyright fields: https://developers.google.com/search/docs/data-types/image-license-metadata
		set_iptc_creator_copyright "$sidecar_file" "$CREATOR" "$photofile"
	fi

	# if we have keywords from an existing sidecar, set these in the new sidecar, too. in case some of these are
	# also in KEYWORDS, the following sidecar_add_iptc_keywords call for the new ones will just skip any existing
	# (old) keywords
	# TODO add new option -O (disable case sensitivity?) which will really overwrite, i.e. no old keywords are kept
	if [[ -v old_keywords ]] && [[ -n $old_keywords ]]; then
		sidecar_add_iptc_keywords "$sidecar_file" "$old_keywords"
	fi

	photo_filename=$(basename "$photofile")
	fullname=${photo_filename%%.*}
	sidecar_set_property "$sidecar_file" "IPTC" "Headline" "$(iptc_headline_from_photofile "$photofile" )"
	sidecar_set_property "$sidecar_file" "IPTC" "Caption" \
		"$(iptc_caption_from "$(photoid "$photofile")" "${DESCRIPTION+$DESCRIPTION}")"
	
	if [[ -n "$lens_from_exif" ]]; then
		iptc_lens="$lens_from_exif;"
	else 
		iptc_lens=""
	fi
	iptc_keywords="RawTherapee;$camera_from_exif;$manufacturer_from_exif;$iptc_lens${KEYWORDS-}"
	sidecar_add_iptc_keywords "$sidecar_file" "$iptc_keywords"

	echo "$sidecar_file"
done
