#! /usr/bin/env bash

set -eu

APP_TITLE="Rename photos"

BASE_DIR="$(dirname "$(readlink -e "$0")")/../.."

source "$BASE_DIR/apps/lib/notification.sh"
source "$BASE_DIR/lib/photofiles.sh"

PATH="$BASE_DIR/apps:$PATH"

if ! [[ -v NAUTILUS_SCRIPT_SELECTED_FILE_PATHS ]]; then
    notify_error "$APP_TITLE" "No photos selected (Env var is not set)"
    exit 1
fi

for file in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS; do
    if is_original_photofile "$file"; then
        echo "$file"
    fi
done | xargs -r rename 
