#! /usr/bin/env bash

set -eu

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."
source "$BASE_DIR/lib/photoid.sh"
PATH="$BASE_DIR/metadata:$PATH"

for photo in "$@"; do
    photoid=$(photoid_get_from_file "$photo")
    title=$(photoid_get_title "$photoid")
    remove_keywords "$title" "$photo"
done

