#! /usr/bin/env bash

set -eu

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."
source "$BASE_DIR/lib/photofiles.sh"
source "$BASE_DIR/metadata/lib/iptc.sh"
source "$BASE_DIR/metadata/lib/xmp.sh"
source "$BASE_DIR/rawtherapee/lib/sidecar.sh"
source "$BASE_DIR/metadata/lib/jpeg_iptc.sh"

declare -r FILE=$(readlink -e "$1")
if [[ -z $FILE ]]; then
    echo "[ERROR] $1 does not exist" >&2
    exit 1
fi

declare -r PHOTOID=$2
if [[ -z $PHOTOID ]]; then
    echo "[ERROR] No photoid given" >&2
    exit 1
fi

is_photoid_only_caption() {
    local -r caption=$1
    [[ "$caption" =~ ^\[$PHOTOID_PATTERN\]\;?$ ]]
}

if is_xmp_sidecar "$FILE"; then
    
    xmp_set_headline "$FILE" "$(iptc_headline_from_photofile "$PHOTOID")"
    
    old_description=$(xmp_get_description "$FILE")
    if [[ -z $old_description ]]; then
        xmp_set_description "$FILE" "$(iptc_create_caption "$PHOTOID")"
    else
        # TODO add check if old_description contains photoid - if not, add it, don't try to update it 
        xmp_set_description "$FILE" "$(iptc_update_caption_photoid "$PHOTOID" "$old_description")"
    fi    

elif is_rawtherapee_sidecar "$FILE"; then
    
    if rt_sidecar_has_property_value "$FILE" "IPTC" "Headline"; then
        headline=$(iptc_headline_from_photofile "$PHOTOID")
        sidecar_set_property "$FILE" "IPTC" "Headline" "$headline"
    fi

    if rt_sidecar_has_property_value "$FILE" "IPTC" "Caption"; then
        old_caption=$(sidecar_get_property "$FILE" "IPTC" "Caption")
        if is_photoid_only_caption "$old_caption"; then
            old_description=""
        else 
            old_description=$(sed -r 's/(.*)\\n\\n\['"$PHOTOID_PATTERN"'\]/\1/' <<<"$old_caption")
        fi    
        
        caption=$(iptc_caption_from "$PHOTOID" "$old_description")
        sidecar_set_property "$FILE" "IPTC" "Caption" "$caption"
    fi

elif is_jpeg "$FILE"; then

    headline=$(iptc_headline_from_photofile "$PHOTOID")
    jpeg_set_iptc "$FILE" "Headline" "$headline"

    # change the title in the caption while taking care of existing description texts:
    # get old_caption and check if it contains more than just the photoid. if yes, get
    # the old description text from old_caption. then pass any old old_description
    # (or none) as extra text to iptc_caption_from
    old_caption=$(jpeg_get_iptc "$FILE" "Caption")
    if is_photoid_only_caption "$old_caption"; then
        old_description=""
    else 
        # so the problem is that the caption from jpeg iptc includes the real linebreaks. 
        # therefore, let's use some head/sed/paste magic to get the old description
        # in the sidecar format (because everything else is based on that):
        # first take everything but the first two lines of old_caption (because that is the 
        # photoid and the preceding blank line) and then join all lines with linebreak literals
        # FIXME what does "$ !" do in the sed pattern?
        old_description=$(head -n -2 <<<"$old_caption" | sed -r '$ ! s/^(.*)$/\1\\n/' |\
            paste -s -d '')
    fi    
    caption=$(iptc_caption_from "$PHOTOID" "$old_description")
    jpeg_set_iptc "$FILE" "Caption" "$caption"

fi