#! /usr/bin/env bash

set -eu
shopt -s nocasematch

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")"
source "$BASE_DIR/strings/strings.sh"
source "$BASE_DIR/rawtherapee/lib/sidecar.sh"
source "$BASE_DIR/lib/jpeg.sh"

PATH="$BASE_DIR/lib:$PATH"


declare -r KEYWORDS=$1
if [[ -z $KEYWORDS ]]; then
	echo "[ERROR] No keywords" >&2
	exit 1
elif [[ -f $KEYWORDS || -d $KEYWORDS ]]; then
	echo "[ERROR] Keywords parameter seems to be a file or directory - actual keywords parameter is missing?" >&2
	exit 1
fi

shift 1

if [[ ${1:-} = "-" ]]; then
    declare -r READ_PHOTOS_FROM_STDIN=
else 
    declare -r PHOTOS=$@
fi

is_rawtherapee_sidecar() {
	local -r file=$1
	[[ $file =~ .*\.pp[23]$ ]]
}

is_converted_jpeg() {
	local -r file=$1
	[[ $file =~ .*/converted/.*\.jpg$ ]]
}

process_rawtherapee_sidecar() {
	local -r sidecar=$1

	if ! [[ -w $sidecar ]]; then
		chmod u+w "$sidecar"
		local -r restore_write_protection=
	fi

	if ! grep -q "^\[IPTC\]$" "$sidecar"; then
		echo -e "\n[IPTC]\nKeywords=;\n" >> $sidecar			
	fi

	sidecar_add_iptc_keywords "$sidecar" "$KEYWORDS"
	
	if [[ -v restore_write_protection ]]; then
		chmod u-w "$sidecar"
	fi	
}

process_converted_jpeg() {
	local -r jpgfile=$1

	if ! [[ -w $jpgfile ]]; then
		chmod u+w "$jpgfile"
		local -r restore_write_protection=
	fi

	jpeg_set_iptc_keywords "$KEYWORDS" "$jpgfile"

	if [[ -v restore_write_protection ]]; then
		chmod u-w "$jpgfile"
	fi
}

apply_add_keywords() {
	local -r file=$1
	if is_rawtherapee_sidecar "$file"; then
		process_rawtherapee_sidecar "$file" && echo "$file"
	elif is_converted_jpeg "$file"; then		
		process_converted_jpeg "$file" && echo "$file"
	fi
}

set -o pipefail
if [[ -v READ_PHOTOS_FROM_STDIN ]]; then
    collect_associated_files.sh < /dev/stdin | while read -r file; do apply_add_keywords "$file"; done
else 
    collect_associated_files.sh "$PHOTOS" | while read -r file; do apply_add_keywords "$file"; done
fi 