#! /usr/bin/env bash

set -eu

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")"

PATH="$BASE_DIR:$PATH"

source "$BASE_DIR/lib/photofiles.sh"

declare -r ARCHIVE_DIR=$(readlink -e "$1")
if ! [[ -e $ARCHIVE_DIR ]]; then
    echo "[ERROR] Archive directory $1 does not exist" >&2
    exit 1
fi
shift 1

if [[ $# = 0 ]]; then
    declare -r READ_PHOTOS_FROM_STDIN=
else 
    declare -r PHOTOS=$@
fi

apply_archive() {
    local -r file=$1
    local -r target="$ARCHIVE_DIR/$(path_relative_to_sourceroot_from_file "$file")"

    if [[ $file == $target ]]; then
        echo "[ERROR] File to archive is identical to target location" >&2
        exit 1
    fi

    if ! [[ -e $(dirname "$target") ]]; then
        mkdir --parents "$(dirname "$target")"
    fi

    if [[ -e $target ]]; then
        echo "[WARN] Target file $target exists, only deleting $file" >&2
        rm "$file"
        return
    fi

    mv "$file" "$target" && chmod a-w "$target" && echo "$target"
}

set -o pipefail
if [[ -v READ_PHOTOS_FROM_STDIN ]]; then
    collect_associated_files < /dev/stdin | while read -r file; do apply_archive "$file" "$file"; done
else 
    collect_associated_files "$PHOTOS" | while read -r file; do apply_archive "$file"; done
fi