#! /usr/bin/env bash

set -e

export PATH="$(dirname $(readlink -e $0)):$PATH"
declare -r MOVE_PHOTOS="$(dirname $(readlink -e $0))/lib/move_photos.sh"
source "$(dirname "$(readlink -e $0)")/lib/metadata.sh"

declare -r SEARCH_DIR=$(readlink -e "$1")
if ! [[ -d $SEARCH_DIR ]]; then
    echo "[EXIT]: $1 is not a directory" >&2
    exit 1
elif [[ -z $(find "$SEARCH_DIR" -type f -path '*/converted/*.jpg') ]]; then
	echo "[EXIT] No processed photos in $SEARCH_DIR" >&2
	exit
fi

declare -r ARCHIVE_DIR=$(readlink -e "$2")
if ! [[ -d $2 ]]; then
	echo "[EXIT] $2 is not a directory" >&2
	exit 1
fi

set -u

# find all processed in SEARCH_DIR
find "$SEARCH_DIR" -type f -path '*/converted/*.jpg' | \
# get fullnames for all processed files
while read -r processed_file; do
	fullname_from_photofile "$processed_file" | sed -r 's/(.+_[0-9a-zA-Z]+)-[0-9]+$/\1/'
done | \
# collect original files
while read -r fullname; do
    find "$SEARCH_DIR" -regextype posix-extended -type f -iregex ".+/$fullname\.(ORF|RAW|JPG|CRW|CR2)$" ! -path '*/converted/*'
done | xargs "$MOVE_PHOTOS" -t "$ARCHIVE_DIR" | xargs chmod ugo-w