#! /usr/bin/env bash

set -eu
shopt -s nocasematch

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")"
source "$BASE_DIR/lib/strings.sh"
source "$BASE_DIR/lib/photofiles.sh"
source "$BASE_DIR/rawtherapee/lib/sidecar.sh"
source "$BASE_DIR/lib/jpeg_iptc.sh"

PATH="$BASE_DIR:$PATH"


declare -r ALBUM=$(echo "${1:-}" | tr ' ' '-')
if [[ -z $ALBUM ]]; then
    echo "[ERROR] Album parameter missing" >&2
    exit 1
elif [[ -f $ALBUM || -d $ALBUM ]]; then
	echo "[ERROR] Album parameter is a file or directory" >&2
	exit 1
fi

shift 1

if [[ $# = 0 ]]; then
    declare -r READ_PHOTOS_FROM_STDIN=
else 
    declare -r PHOTOS=$@
fi

apply_change_album() {
    local -r file=$1
    local -r old_album_path=$(albumpath_from_file "$file")

    if [[ $(basename "$old_album_path") = $ALBUM ]]; then
        echo "[WARN] Cannot change album of $file to \"$ALBUM\", same as old album" >&2
        return
    fi

    local -r relative_to_album_path=$(path_relative_to_album_from_file "$file")
    local -r newfullpath="$(dirname "$old_album_path")/$ALBUM/$relative_to_album_path"

    # this is a real error case unlike the other check above (which stems from careless user input)
    if [[ -e $newfullpath ]]; then
        echo "[ERROR] Cannot change album of $file, file exists already in \"$ALBUM\": $newfullpath" >&2
        exit 1
    fi

    if ! [[ -e $(dirname "$newfullpath") ]]; then
        mkdir --parents "$(dirname "$newfullpath")"
    fi
    
    mv "$file" "$newfullpath"
    
    echo "$newfullpath"
}

set -o pipefail
if [[ -v READ_PHOTOS_FROM_STDIN ]]; then
    collect_associated_files < /dev/stdin | while read -r file; do apply_change_album "$file"; done
else 
    collect_associated_files "$PHOTOS" | while read -r file; do apply_change_album "$file"; done
fi