#! /usr/bin/env bash

set -eu
set -o pipefail

declare -r BASEDIR="$(dirname "$(readlink -e "$0")")"

source "$BASEDIR/lib/photofiles.sh"
source "$BASEDIR/lib/photoid.sh"
source "$BASEDIR/util/unprotect.sh"
source "$BASEDIR/rawtherapee/lib/sidecar.sh"
source "$BASEDIR/metadata/lib/xmp.sh"

PATH="$BASEDIR/metadata:$BASEDIR:$BASEDIR/lib:$PATH"


function lookupTitle() {
    local photofile=$1

    local title_from_photoid=$(photoid_get_title "$(photoid_get_from_file "$photofile")")

    if ! [[ $title_from_photoid =~ - ]]; then
        
        echo "$title_from_photoid"

    else 

        # Try to get headline from XMP file
        local xmp_file="${photofile%.*}.xmp"
        if [[ -f "$xmp_file" ]]; then
            
            local xmp_headline=$(xmp_get_headline "$xmp_file")
            if [[ -n "$xmp_headline" ]]; then
                echo "${xmp_headline% *}" 
                return 0
            fi
        fi
        
        # Try to get Caption from rawtherapee sidecar
        # TBD it might be that filename schema (only apped "ppN" and keep the original extension) was not yet used for pp2. 
        for sidecar in "$photofile".pp3 "$photofile".pp2; do
            if [[ -f "$sidecar" ]]; then
                local sidecar_headline=$(sidecar_get_property "$sidecar" "IPTC" "Headline")
                if [[ -n "$sidecar_headline" ]]; then
                    echo "${sidecar_headline% *}" 
                    return 0
                fi
            fi
        done

        # Fallback to title from photoid
        echo "$title_from_photoid"

    fi
}


while getopts "krf:" opt; do
    case $opt in
        k ) 
            ADD_TITLE_KEYWORD=;;
        r )
            REMOVE_OLD_TITLE_KEYWORD=;;
        f )
            mapfile -t PHOTO_FILES < "$OPTARG";;
        * ) 
            echo "Usage: $0 [-k] [-r] -f <photos_file> <new_title>"
            exit 1;;    
	esac
done
shift $(expr $OPTIND - 1 )


declare -r NEW_TITLE=${1:-}
if [[ -z $NEW_TITLE ]]; then
    echo "[ERROR] Title parameter missing" >&2
    exit 1
elif [[ -f $NEW_TITLE ]]; then
	echo "[ERROR] Title parameter is a file" >&2
	exit 1
fi
shift 1


if ! [[ -v PHOTO_FILES ]] && [[ $# -gt 0 ]]; then
    PHOTO_FILES=("$@")
elif ! [[ -v PHOTO_FILES ]] || [[ ${#PHOTO_FILES[@]} -eq 0 ]]; then
    echo "[ERROR] No photos" >&2
    exit 1
fi


echo "[INFO] Changing titles of ${#PHOTO_FILES[@]} photos to \"$NEW_TITLE\"" >&2


safe_new_title=$(tr ' ' '-' <<<"$NEW_TITLE")
for photo in "${PHOTO_FILES[@]}"; do

    echo "[INFO] $photo" >&2

    old_photoid=$(photoid_get_from_file "$photo")
    new_photoid=$(photoid_set_title "$old_photoid" "$safe_new_title")

    if [[ "$old_photoid" == "$new_photoid" ]]; then
        echo "[INFO] Title of $photo is already \"$NEW_TITLE\", skipping" >&2
        continue
    fi

    if [[ -n $(find "$(dirname "$photo")" -type f -name "$new_photoid.*") ]]; then
        echo "[WARN] Found existing file with new title, skipping $photo" >&2
        continue      
    fi

    # Let's consider calling lookupTitle a costly operation so we only do it once if required
    if [[ -v REMOVE_OLD_TITLE_KEYWORD ]]; then
        old_title=$(lookupTitle "$photo")
    fi    

    collect_associated_files "$photo" | while read -r old_file; do 

        # TODO check if target file exists already.

        unprotect_file_if_needed "$old_file"

        set_metadata-title "$old_file" "$NEW_TITLE"
        set_metadata-description-photoid "$old_file" "$new_photoid"

        if [[ -v REMOVE_OLD_TITLE_KEYWORD ]]; then
            update_keywords "-$old_title" "$old_file"
        fi

        if [[ -v ADD_TITLE_KEYWORD ]]; then
            update_keywords "$NEW_TITLE" "$old_file"
        fi        

        reprotect_check_file "$old_file"
        

        old_file_extension="${old_file#*.}"
        new_file="$(dirname "$old_file")/$new_photoid.$old_file_extension"
        
        mv "$old_file" "$new_file"

        echo "$new_file"

    done

done