#! /usr/bin/env bash

set -eu
set -o pipefail

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")"
source "$BASE_DIR/lib/directories.sh"
source "$BASE_DIR/lib/photoid.sh"
source "$BASE_DIR/metadata/lib/xmp.sh"

PATH="$BASE_DIR/metadata:$BASE_DIR:$PATH"


function lookupOldAlbumName() {
    local photofile=$1
    
    # get album name from path (album directory)
    old_album_path=$(directories_get_albumpath_from_file "$photofile")
    old_album=${old_album_path##*/}

    # if we have dashes in the album name, try to find in xmp keywords
    if [[ $old_album =~ - ]]; then

        local xmp_file="${photofile%.*}.xmp"
        if [[ -f "$xmp_file" ]]; then
            local old_album_pattern="^${old_album//-/[- ]}$"
            xmp_list_keywords "$xmp_file" | while read -r keyword; do
                if [[ $keyword =~ $old_album_pattern ]]; then
                    echo "$keyword"
                    return 0
                fi
            done
        fi

        # TODO add lookup in sidecar

        echo "${old_album//-/ }"
        
    else
        echo "$old_album"
    fi
}


while getopts "taof:" opt; do
    case $opt in
        t ) CHANGE_PHOTO_TITLES_TO_ALBUM_NAME=;;
        a ) ADD_NEW_ALBUM_KEYWORD=;;
        o ) REMOVE_OLD_ALBUM_KEYWORD=;;
        f )
            mapfile -t PHOTO_FILES < "$OPTARG";;
	esac
done
shift $(expr $OPTIND - 1 )


declare -r NEW_ALBUM=$1
if [[ -f $NEW_ALBUM ]]; then
	echo "[ERROR] Album parameter is a file" >&2
	exit 1
fi
shift 1


if ! [[ -v PHOTO_FILES ]] && [[ $# -gt 0 ]]; then
    PHOTO_FILES=("$@")
elif ! [[ -v PHOTO_FILES ]] || [[ ${#PHOTO_FILES[@]} -eq 0 ]]; then
    echo "[ERROR] No photos" >&2
    exit 1
fi

echo "[INFO] Moving ${#PHOTO_FILES[@]} photos to album \"$NEW_ALBUM\"" >&2

safe_new_album=$(tr ' ' '-' <<<"$NEW_ALBUM")
for photo in "${PHOTO_FILES[@]}"; do

    echo "[INFO] $photo" >&2

    old_album_path=$(directories_get_albumpath_from_file "$photo")
    photo_relative_to_album=${photo#$old_album_path/}
    album_parent=${old_album_path%/*}
    new_album_path="$album_parent/$safe_new_album"

    if [[ -e "$new_album_path/$(dirname "$photo_relative_to_album")/$(basename "$photo")" ]]; then
        echo "[ERROR] Cannot move $photo to $NEW_ALBUM, file exists already" >&2
        continue
    fi

    if [[ -v REMOVE_OLD_ALBUM_KEYWORD ]]; then
        old_album_name=$(lookupOldAlbumName "$photo")
    fi

    collect_associated_files "$photo" | while read -r file_in_old_album; do 

        file_relative_to_album=${file_in_old_album#$old_album_path/}
        file_in_new_album="$new_album_path/$(dirname "$file_relative_to_album")/$(basename "$file_in_old_album")"

        if [[ -e $file_in_new_album ]]; then
            echo "[ERROR] Cannot move $file_in_old_album to $NEW_ALBUM, target file exists, continuing" >&2
            continue
        fi


        if [[ -v REMOVE_OLD_ALBUM_KEYWORD ]]; then
            update_keywords "-$old_album_name" "$file_in_old_album" 
        fi

        if [[ -v ADD_NEW_ALBUM_KEYWORD ]]; then
            update_keywords "$NEW_ALBUM" "$file_in_old_album"
        fi    


        if ! [[ -e $(dirname "$file_in_new_album") ]]; then
            mkdir --parents "$(dirname "$file_in_new_album")"
        fi
        mv "$file_in_old_album" "$file_in_new_album"
        echo "$file_in_new_album"

    done

    # TODO print the album-relative path of each file from the while loop. for each entry, create params for mv by concatenating
    # with the new album path, and then after the loop mv all files at once. Also create the directory structure only now (i.e. check will be
    # only once).
    # This will replace copying each files separately and prevents confusion from files having already disappeared from the old album.
    # -> with that changed, we can also add again the check from update_metadata (keywords parameter is not a file or directory - which 
    # was the case when adding the album name as a keyword and running the script in the new album's parent directory)

    if [[ -v CHANGE_PHOTO_TITLES_TO_ALBUM_NAME ]]; then
        change_photo_title "$NEW_ALBUM" "$new_album_path/$(dirname "$photo_relative_to_album")/$(basename "$photo")" 
    fi

done
