#! /usr/bin/env bash

set -u

declare -r APP_TITLE="Import photos"

declare -r BASE_DIR=$(dirname "$(readlink -e "$0")")

declare -r POPUP_CMD="$BASE_DIR/utils/notification"
declare -r IMPORT_CMD="$BASE_DIR/import_photos"
declare -r CREATE_SIDECAR_CMD="$BASE_DIR/profile-builder/create_sidecar"
declare -r YAD_CMD="$BASE_DIR/utils/yad"
source "$BASE_DIR/utils/yad_helpers.sh"


while getopts "c:" opt; do
    case $opt in
        c ) 
			declare -r CREATOR_OPTION=$OPTARG;;
	esac
done
shift $(expr $OPTIND - 1 )


declare -r DCIM_DIR=${1+$1}
declare -r TARGET_DIR=${2+$2}
declare -r SIDECAR_TEMPLATES_DIR=${3+$3}

dialog_txt="$(echo -e "Import photos from\n\t$DCIM_DIR\nto\n\t$TARGET_DIR:\n")"
options_string=$("$YAD_CMD" \
    --title="$APP_TITLE" \
    --text="$dialog_txt" \
    --form \
    --field="Album:TEXT" "New photos" \
    --field="Photo title:TEXT" "" \
    --field="Photographer/creator:TEXT" "${CREATOR_OPTION+$CREATOR_OPTION}" \
    --field="Keywords (separated by \";\"):TEXT" "" \
    --field="Only from date:DT" 2> /dev/null)
yad_rc=$?
if [[ $yad_rc = 252 ]] || [[ $yad_rc = 1 ]]; then
    exit
fi

declare -r ALBUM="$(echo "$options_string" | cut -d'|' -f 1 | tr ' ' '-')"

title_string="$(echo "$options_string" | cut -d'|' -f 2 | tr ' ' '-')"
test -n "$title_string" && declare -r TITLE="$title_string"

creator_string="$(echo "$options_string" | cut -d'|' -f 3)"
test -n "$creator_string" && declare -r CREATOR=$creator_string

keywords_string="$(echo "$options_string" | cut -d'|' -f 4)"
test -n "$keywords_string" && declare -r KEYWORDS=$keywords_string

# declare -r DATE_TAKEN="$(echo "$options_string" | cut -d'|' -f 5)"


imported_photos=$("$IMPORT_CMD" ${ALBUM+-a "$ALBUM"} ${TITLE+-t "$TITLE"} "$DCIM_DIR" "$TARGET_DIR")
import_photos_rc=$?
if [[ $import_photos_rc != 0 ]]; then
    case $import_photos_rc in     
        101 )
            error_msg="Import failed, DCIM directory missing";;
        102 )
            error_msg="Import failed, target directory missing";;
        * )
            error_msg="Import failed with return code $import_photos_rc";;
    esac
    "$POPUP_CMD" -e "$APP_TITLE" "$error_msg"
    exit 1
fi

create_sidecar_out=$("$CREATE_SIDECAR_CMD" ${CREATOR+-c "$CREATOR"} ${KEYWORDS+-k "$KEYWORDS"} "$SIDECAR_TEMPLATES_DIR" $(echo $imported_photos) 2>&1)
create_sidecar_rc=$?
if [[ $create_sidecar_rc != 0 ]]; then
    case $import_photos_rc in     
        101 )
            error_msg=", templates directory missing";;
        102 )
            error_msg=", templates directory is not a directory (only photos given?)";;
        * )
            error_msg=" with return code $create_sidecar_rc";;
    esac
    "$POPUP_CMD" -e "$APP_TITLE" "Import succeeded but creating sidecars failed $error_msg"
    exit 1
fi


total_size_mb=$(du -ch $imported_photos | tail -1 | cut -f 1)
imported_photos_count=$(echo "$imported_photos" | wc -l)
duration_in_minutes=$(( $SECONDS / 60 ))
if echo "$create_sidecar_out" | grep -q "\[ERROR\]"; then
    create_sidecar_errors="Errors when creating sidecars:\n$(echo "$create_sidecar_out" | grep "\[ERROR\]")"
fi
"$POPUP_CMD" -i "$APP_TITLE" \
    "$(echo -e "Done, imported $imported_photos_count photos ($total_size_mb MB) in $duration_in_minutes minutes.${create_sidecar_errors+$(echo -e "\n\n$create_sidecar_errors")}")"