#! /usr/bin/env bash

set -eu

declare -r MOVE_PHOTOS="$(dirname $(readlink -e $0))/lib/move_photos.sh"

while getopts "r" opt; do
    case $opt in
        r ) 
            declare -r RENAME_PHOTOS=;;
	esac
done
declare -r RENAME_MODE=$(test -v RENAME_PHOTOS && echo "b" || echo "a")
shift $(expr $OPTIND - 1)

declare -r TARGET_ALBUM_NAME=${1+$1}
if [[ -z $TARGET_ALBUM_NAME ]]; then
    echo "[ERROR] Target album name parameter is missing" >&2
    exit 1
elif [[ -e $TARGET_ALBUM_NAME ]]; then
    echo "[ERROR] $TARGET_ALBUM_NAME seems to be a file or directory but not the target album name" >&2
    exit 1
fi
shift 1
declare -r PHOTOS_TO_MOVE=$@

"$MOVE_PHOTOS" -r "$TARGET_ALBUM_NAME" -m $RENAME_MODE $PHOTOS_TO_MOVE 
