#! /usr/bin/env bash

set -e

export PATH="$(dirname "$(readlink -e "$0")"):$PATH"
declare -r MOVE_PHOTOS="$(dirname $(readlink -e $0))/lib/move_photos.sh"

while getopts "r" opt; do
    case $opt in
        r ) declare -r RENAME_PHOTOS=;;
	esac
done
declare -r RENAME_MODE=$(test -v RENAME_PHOTOS && echo "b" || echo "a")
shift $(expr $OPTIND - 1)

declare -r TARGET_ALBUM_NAME=$1
shift 1
declare -r PHOTOS_TO_MOVE=$@

set -u

"$MOVE_PHOTOS" -r "$TARGET_ALBUM_NAME" -m $RENAME_MODE $PHOTOS_TO_MOVE 
