#! /usr/bin/env bash

set -e

export PATH="$(dirname $(readlink -f "$0")):$PATH"

declare -r NEW_NAME=$1
if [[ -z $NEW_NAME ]]; then
    echo "Parameter with new name is missing" >&2
    exit 1
fi

shift 1
declare -r PHOTOS_TO_RENAME=$@

set -u

move_photos -r "$NEW_NAME" -m "p" $PHOTOS_TO_RENAME