#! /usr/bin/env bash

set -eu

BASE_DIR=$(dirname "$(readlink -e "$0")")
PATH="$BASE_DIR:$BASE_DIR/apps:$BASE_DIR/util:$BASE_DIR/lib:$PATH"

selector | collect_associated_files -i | while read -r file; do 
    filename=${file##*/}
    photoid=${filename%%.*}
    run_sidestep_writeprotect "$file" set_title_in_iptc "$file" "$photoid"
done