#! /usr/bin/env bash

set -eu

BASE_DIR=$(dirname "$(readlink -e "$0")")
source "$BASE_DIR/util/unprotect.sh"
PATH="$BASE_DIR/metadata:$BASE_DIR:$BASE_DIR/apps:$BASE_DIR/lib:$PATH"

selector | collect_associated_files -i | while read -r file; do 
    filename=${file##*/}
    photoid=${filename%%.*}
    unprotect_file_if_needed "$file"
    set_photoid "$photoid""$file"
    reprotect_check_file "$file"
done