#! /usr/bin/env bash

set -eu
shopt -s nocasematch

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")"
source "$BASE_DIR/lib/strings.sh"
source "$BASE_DIR/lib/metadata.sh"
source "$BASE_DIR/rawtherapee/lib/sidecar.sh"
source "$BASE_DIR/lib/jpeg_iptc.sh"

PATH="$BASE_DIR/lib:$PATH"

while getopts "f" opt; do
    case $opt in
        f ) 
			declare -r FORCE_OVERWRITE=;;
	esac
done
shift $(expr $OPTIND - 1 )


declare -r TITLE=$(echo "${1:-}" | tr ' ' '-')
if [[ -z $TITLE ]]; then
    echo "[ERROR] Title parameter missing" >&2
    exit 1
elif [[ -f $TITLE || -d $TITLE ]]; then
	echo "[ERROR] Title parameter is a file or directory" >&2
	exit 1
fi

shift 1

if [[ $# = 0 ]]; then
    declare -r READ_PHOTOS_FROM_STDIN=
else 
    declare -r PHOTOS=$@
fi


new_filename() {
    local -r filename=$1
    local -r newtitle=$2

    echo "${newtitle}_${filename#*_}"
}

old_title() {
    local file=$1
    local basename=$(basename "$1")
    echo ${basename%%_*}
}

is_rawtherapee_sidecar() {
	local -r file=$1
	[[ $file =~ .*\.pp[23]$ ]]
}

is_converted_jpeg() {
	local -r file=$1
	[[ $file =~ .*/converted/.*\.jpg$ ]]
}

apply_set_title() {

    local -r file=$1
    local -r filename=${file##*/}

    if ! [[ -v FORCE_OVERWRITE ]] && [[ $(old_title "$file") = $TITLE ]]; then
        echo "[WARN] Cannot change title of $file to \"$TITLE\", same as old title" >&2
        return
    fi    

    if ! [[ -w $file ]]; then
        chmod u+w "$file"
        local -r restore_write_protection=
    fi

    local -r newfile="$(dirname "$file")/$(new_filename "$filename" "$TITLE")"

    # this is a real error case unlike the other check above (which stems from careless user input)
    if [[ -e $newfile ]] && ! [[ -v FORCE_OVERWRITE ]]; then
        echo "[ERROR] Cannot change title of $file to \"$TITLE\", file $newfile exists already" >&2
        exit 1
    fi

    if is_rawtherapee_sidecar "$file"; then
        sidecar_set_property "$file" "IPTC" "Headline" "$(headline_from_photofile "$newfile")"
        sidecar_set_property "$file" "IPTC" "Caption" "[$(fullname_from_photofile "$newfile")]"
    elif is_converted_jpeg "$file"; then
        jpeg_set_iptc "$file" "Headline" "$(headline_from_photofile "$newfile")"
        jpeg_set_iptc "$file" "Caption" "[$(fullname_from_photofile "$newfile")]"
    fi


    # do an additional check if $newfile exists because we might have skipped the check above because we're in 
    # FORCE_OVERWRITE mode
    ! test -e "$newfile" && mv "$file" "$newfile"

    if [[ -v restore_write_protection ]]; then
        chmod u-w "$newfile"
    fi

    echo "$newfile"
}

set -o pipefail
if [[ -v READ_PHOTOS_FROM_STDIN ]]; then
    collect_associated_files.sh < /dev/stdin | while read -r file; do apply_set_title "$file"; done
else 
    collect_associated_files.sh "$PHOTOS" | while read -r file; do apply_set_title "$file"; done
fi 