#! /usr/bin/env bash

set -e
shopt -s nocasematch

declare -r COLLECTOR_CMD=$(dirname "$0")/lib/collect_associated_files.sh

declare -r KEYWORDS=$1
if [[ -z $KEYWORDS ]]; then
	echo "No keywords" >&2
	exit 1
elif [[ -f $KEYWORDS || -d $KEYWORDS ]]; then
	echo "Keywords parameter seems to be a file or directory - actual keywords parameter is missing?"
	exit 1
fi

shift 1
declare -r FILES=$@

set -u

set_iptc_in_sidecar() {
	local -r sidecar_file=$1
	local new_keywords=

	local -r OLD_IFS=$IFS
	IFS=";"

	local old_keywords=$(sed -rn '/\[IPTC\]/,/^$/s/Keywords=(.+);+$/\1/p' "$sidecar_file")
	for old_keyword in $old_keywords; do 
		if ! [[ $KEYWORDS =~ .*$old_keyword.* ]]; then
			new_keywords="$new_keywords;$old_keyword"
		fi		
	done

	for new_keyword in $KEYWORDS; do
		if [[ $new_keyword =~ .+[[:space:]].+ ]]; then
			new_keyword="\"$new_keyword\""
		fi
		new_keywords="$new_keywords$new_keyword;"
	done

	IFS=$OLD_IFS

	sed -i '/\[IPTC\]/,/^$/ s/Keywords=.*;$/Keywords='"$new_keywords"'/' "$sidecar_file"
}

set_iptc_in_jpeg() {
	set -x
	local -r jpeg_file=$1
	local -r old_keywords=$(exiv2 -PIt -K Iptc.Application2.Keywords $jpeg_file 2> /dev/null)

	local -r OLD_IFS=$IFS
	IFS=";"

	for new_keyword in $KEYWORDS; do
		if [[ $old_keywords =~ .*$new_keyword.* ]]; then
			echo "[SKIP] Keyword '$old_keyword'" >&2
		fi

		if [[ $new_keyword =~ .+[[:space:]].+ ]]; then
			new_keyword="\"$new_keyword\""
		fi
		exiv2 -M "add Iptc.Application2.Keywords $new_keyword" "$jpeg_file" 2> /dev/null
	done

	IFS=$OLD_IFS
	set +x
}


"$COLLECTOR_CMD" $FILES | while read -r file; do

	if [[ $file =~ .*\.pp[23]$ ]]; then

		if ! grep "^[IPTC]$" "$file"; then
			echo -e "\n[IPTC]\nKeywords=;\n" >> $file			
		fi

		# FIXME remove write-protection and restore afterwards
		set_iptc_in_sidecar "$file"

	elif [[ $file =~ .*/converted/.*\.jpg$ ]]; then
		# FIXME remove write-protection and restore afterwards
		set_iptc_in_jpeg "$file"
	fi
	
done