#! /usr/bin/env bash

set -eu

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."
source "$BASE_DIR/lib/photofiles.sh"
source "$BASE_DIR/metadata/lib/jpeg_iptc.sh"

PATH="$(dirname "$(readlink -e "$0")"):$PATH"

search_dir=$(readlink -e "$1")
if [[ -z $search_dir ]]; then
    echo "[ERROR] search dir $search_dir does not exist" >&2
    exit 1
fi

timestamp_file=$(readlink -e "$2")
if [[ -z $timestamp_file ]]; then
    echo "[ERROR] timestamp file $timestamp_file does not exist" >&2
    exit 1
fi

# We're already sorting as oldest-first here so that they will be imported with correct
# publication order (publication order should follow the order in which the photos were
# post-processed)
find "$search_dir" -regextype posix-extended -type f -cnewer "$timestamp_file" \
    -iregex "$OUTPUT_DIR_PATTERN/$PHOTOID_PATTERN\.jpg" -printf "%T@ %p\n" | sort | cut -d' ' -f2