#! /usr/bin/env bash

set -eu

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."
source "$BASE_DIR/lib/photofiles.sh"
source "$BASE_DIR/lib/jpeg_iptc.sh"

search_dir=$(readlink -e "$1")
if [[ -z $search_dir ]]; then
    echo "[ERROR] search dir $search_dir does not exist" >&2
    exit 1
fi

timestamp_file=$(readlink -e "$2")
if [[ -z $timestamp_file ]]; then
    echo "[ERROR] timestamp file $timestamp_file does not exist" >&2
    exit 1
fi

find "$search_dir" -regextype posix-extended -type f -cnewer "$timestamp_file" \
    -iregex "$OUTPUT_DIR_PATTERN/$PHOTOID_PATTERN\.jpg" |\
while read -r file; do 

    title="$(jpeg_get_iptc "$file" "Headline")"
    album=$(albumname_from_file "$file")

    echo "$file|$title|$album"
done
