#! /usr/bin/env bash

set -eu

source_dir=$1

# TODO use patterns from photofiles.sh
# FIXME get album from iptc
find  "$source_dir"  -type f -iregex ".+/converted/[^/]+\.jpg" -printf '%p\n' |\
    sed -r 's|.*/[0-9]{4}/([^/]+)/[0-9]{4}-[0-9]{2}-[0-9]{2}/converted/(.+)|\1 \2|' | sort -u