#! /usr/bin/env bash

set -eu

PATH="$(dirname "$(readlink -e "$0")"):$PATH"

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."
source "$BASE_DIR/lib/photofiles.sh"
source "$BASE_DIR/lib/jpeg_iptc.sh"

function get_audience() {
    local photofile=$1
    local private_keywords=$2
    if [[ -z $private_keywords ]] || is_private "$photofile" "$private_keywords"; then
        echo "private"
    else 
        echo "public"
    fi
}

function print_file_album_photoid() {
    local -r file=$(readlink -m "$1")

    local title="$(jpeg_get_iptc "$file" "Headline")"
    if [[ -z $title ]]; then
        title="$(title_from_photoid "$file") $(fullnumber_from_photoid "$file")"
    fi
    local album=$(albumname_from_file "$file")
    local audience=$(get_audience "$file" "$private_keywords")

    echo "$file|$title|$album|$audience"
}


private_keywords=$1

shift 1

if [[ $1 == "-" ]]; then
    while read -r file; do print_file_album_photoid "$file"; done < /dev/stdin
else
    for file in $*; do print_file_album_photoid "$file"; done
fi
