#! /usr/bin/env bash

set -eu

PATH="$(dirname "$(readlink -e "$0")"):$PATH"

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."
source "$BASE_DIR/lib/photofiles.sh"
source "$BASE_DIR/lib/jpeg_iptc.sh"

function print_metadata() {
    local -r file=$(readlink -m "$1")

    local title="$(jpeg_get_iptc "$file" "Headline")"
    if [[ -z $title ]]; then
        title="$(title_from_photoid "$file") $(fullnumber_from_photoid "$file")"
    fi
    local album=$(albumname_from_file "$file")
    local audience=$(get_audience_from_iptc_keywords "$file")

    echo "$file|$title|$album|$audience"
}

if [[ $1 == "-" ]]; then
    while read -r file; do print_metadata "$file"; done < /dev/stdin
else
    for file in $*; do print_metadata "$file"; done
fi
