#! /usr/bin/env bash

set -eu

declare -r BASE_DIR=$(readlink -e "$(dirname "$0")/..")
source "$BASE_DIR/lib/photofiles.sh"
source "$BASE_DIR/lib/jpeg_iptc.sh"

function keywords_csv_to_egrep_pattern() {
    local -r csv_list=$1
    OLD_IFS=$IFS
    IFS=";"
    for keyword in $csv_list; do 
        echo "$keyword"
    done | paste -s -d '|' -
    IFS=$OLD_IFS
}

photofile=$1
private_keywords_pattern=$(keywords_csv_to_egrep_pattern $2)

jpeg_get_iptc "$photofile" "Keywords" | grep -E -q "$private_keywords_pattern"
