#! /usr/bin/env bash

set -eu

source "$(dirname "$0")/builder_lib.sh"

#   \1 title
#   \2 day as YYYYMMDD
#   \3 time of day as HH:MM
#   \4 photo number with optional variant, e.g. "2343423" or "343434-5"
#   \5 variant, unused/grouping only
#   \6 file extension
declare -r SED_PATTERN='([a-zA-Z_]+)_([0-9]{8})_([0-9]{4})-([0-9]+(-[0-9]+)?)\.([a-z0-9]{3})'

function uppercase_first_chars() (
    for title_part in $(tr "-" "\n" < /dev/stdin); do
        echo ${title_part^}
    done | paste -s -d '-' -
)

camera=$1

while read -r import_item; do  
    
    source=$(source_from_import_item "$import_item")
    source_file=$(basename "$source")
    source_dir=$(dirname "$source")

    title=$(sed -r 's/'"$SED_PATTERN"'/\1/' <<<$source_file | tr _ - | uppercase_first_chars)
    day=$(sed -r 's/'"$SED_PATTERN"'/\2/' <<<$source_file)
    time=$(sed -r 's/'"$SED_PATTERN"'/\3/' <<<$source_file)
    number=$(sed -r 's/'"$SED_PATTERN"'/\4/' <<<$source_file)
    extension=$(sed -r 's/'"$SED_PATTERN"'/\6/' <<<$source_file)

    target_filename="${title}_${day}_${time}_${camera}_${number}.${extension}"

    if [[ $source_dir =~ .+/converted ]]; then
        echo_item_added_targetpath "$import_item" "converted/$target_filename"
    else 
        echo_item_added_targetpath "$import_item" "$target_filename"
    fi
    
done < /dev/stdin
