#! /usr/bin/env bash

set -eu

source "$(dirname "$0")/builder_lib.sh"

while read -r import_item; do
    source=$(cut -d'|' -f1 <<<"$import_item")
    source_file=${source##*/}

    day=$(sed -r 's/[a-z_]+_([0-9]+)_[0-9]+-[0-9]+(-[0-9])?.[a-zA-Z]+/\1/' <<<$source_file)
    day_dir="${day:0:4}-${day:4:2}-${day:6:2}"    

    echo_item_added_targetpath "${import_item}" "${day_dir}"
done < /dev/stdin