#! /usr/bin/env bash

set -eu

BASE_DIR="$(dirname "$(readlink -e "$0")")/.."
source "$BASE_DIR/metadata/lib/exif.sh"

while getopts "c" opt; do
    case $opt in
        # if -c is given, a "c" or "r" will be added to the photonumber, to communicate whether this is a straight-out-of-camera photo
        # ("c") or a raw photo ("r")
        c ) declare -r ADD_CREATION_SIGNIFIER=;;
	esac
done
shift $(expr $OPTIND - 1 )

photofile=$1

get_file_basename() {
    local filename=${1##*/}
    echo ${filename%%.*}
}

build_from_canon_exif_filenumber() {
    # e.g. "100-2071"
    local canon_filenumber=$(exiv2 -Pt -g 'Exif.Canon.FileNumber' "$1" 2> /dev/null)
    echo ${canon_filenumber/-/}
}

build_from_olympus_filename() {
    # format of photo number: <COLORSPACE><MONTH><DAY><NUMBER>
    # COLORSPACE is either P (for RGB) or _ (for Adobe), thrown away
    # MONTH is 1 to 9 for January to September and A, B, C for October to December
    # DAY is a regular 1-31 day value
    # NUMBER is a four-digit number

    local -r photofile_path=$1
    local -r photofile_name=$(basename "$photofile_path")
    local -r without_ext=${photofile_name%%.*}
    # Convert the stupid A, B, C months to proper numbers 10, 11, 12, prepend a 0 to the others to 
    # have a uniform length
    if [[ $without_ext =~ [P_][ABC][0-9]+ ]]; then
        case ${without_ext:1:1} in 
            A ) echo "10${without_ext:2}";;
            B ) echo "11${without_ext:2}";;
            C ) echo "12${without_ext:2}";;
        esac
    else 
        echo "0${without_ext:1}"
    fi
}

build_from_prefixed_filename() {
    local -r file_basename=$(basename "$1")
    local -r prefix=$2
    local -r prefix_removed=${file_basename#$prefix}
    echo ${prefix_removed%%.*}    
}

build_from_android_filename() {
    # Android filename follow the "yyyymmdd_hhmmss.ext" format so we just concatenate the two parts.
    local basename=$(get_file_basename "$1")
    echo "${basename/_/}"
}

get_creation_signifier() {
    local photo_filename=$1
    local -r extension=${photo_filename##*.}
    if [[ $extension == "JPG" ]]; then
        echo "c"
    else
        echo "r"
    fi
}

camera=$(lookup_camera_from_exif "$photofile")
case "$camera" in 
        DMC-FZ50 )
            photonumber=$(build_from_prefixed_filename "$photofile" "P");; 
        CanonPowerShot* )
            photonumber=$(build_from_canon_exif_filenumber "$photofile");;
        E-M10|E-M5MarkIII )
            photonumber=$(build_from_olympus_filename "$photofile");;
        DSC-RX100M3 )
            photonumber=$(build_from_prefixed_filename "$photofile" "DSC");;   
        SM-G973F )
            photonumber=$(build_from_android_filename "$photofile");; 
        * )
            echo "[ERROR] Unknown camera $camera" >&2
            exit 1;;
esac

if [[ -v ADD_CREATION_SIGNIFIER ]]; then
    echo "$photonumber$(get_creation_signifier "$photofile")"
else 
    echo "$photonumber"
fi

