#! /usr/bin/env bash

set -eu

declare -r BASEDIR="$(dirname "$(readlink -e "$0")")/.."
source "$BASEDIR/lib/photofiles.sh"
source "$BASEDIR/lib/iptc.sh"
source "$BASEDIR/lib/exif.sh"
source "$BASEDIR/lib/strings.sh"
source "$BASEDIR/lib/xmp.sh"

while getopts "c:k:d:or" opt; do
    case $opt in
        c ) 
			creator=$OPTARG;;   
		k ) 
			# CSV string, using ";". no quoting needed for keywords with blanks
			user_keywords=$OPTARG;;
		d )
			description=$OPTARG;;
        o ) 
            overwrite=;;
	esac
done
shift $(expr $OPTIND - 1 )

photofiles=$*

for photofile in $photofiles; do
    photofile_filename=$(basename "$photofile")
    photofile_basename=${photofile_filename%.*}

    # Prepare xmp file
    xmp_file=$(xmp_file_from_photofile "$photofile")
    if ! [[ -v overwrite ]] && [[ -e $xmp_file ]]; then
        echo "XMP file $xmp_file exists already, exiting" >&2
        exit 1
    fi
    create_blank_xmp "$photofile"

    # creator 
    write_xmp_creator "$photofile" "$creator"

    # copyright
    year_from_exif=$(exiftool -s3 -DateTimeOriginal "$photofile" | cut -d':' -f 1)
    if [[ -v creator ]]; then
        copyright="Copyright (c) $creator $year_from_exif"
    else
        copyright="Copyright (c) $year_from_exif"
    fi
    write_xmp_copyright "$photofile" "$copyright"

    # iptc caption
    photofile_basename=${photofile_filename%.*}
    iptc_caption="$(iptc_create_caption "$photofile_basename" "${description+$description}")"
    write_xmp_description "$photofile" "$iptc_caption"

    # iptc headline
    iptc_headline=$(iptc_headline_from_photofile "$photofile")
    write_xmp_headline "$photofile" "$iptc_headline"

    # iptc keywords
    if [[ -v user_keywords ]]; then 
        write_xmp_keywords_from_csv_string "$photofile" "$user_keywords"
    fi
    camera_from_exif=$(lookup_camera_from_exif "$photofile")
    add_xmp_keyword "$photofile" "$camera_from_exif"
    lens_from_exif=$(lookup_lens_from_exif "$photofile")
    if [[ -n $lens_from_exif ]]; then
        add_xmp_keyword "$photofile" "$lens_from_exif" 
    fi
    manufacturer_from_exif=$(lookup_manufacturer_from_exif "$photofile")
    add_xmp_keyword "$photofile" "$manufacturer_from_exif" 
    add_xmp_keyword "$photofile" "RawTherapee" 

done
