#! /usr/bin/env bash

# Allows running a script or program that changes a file which may be write-protected.
# Makes files writeable if needed, executes what was passed as options after the first
# (file) parameter, then restores original write protection (if there had been one).

set -eu

file=$1
shift 1

if ! [[ -w $file ]]; then
    chmod u+w "$file"
    declare -r RESTORE=
fi

"$@"

if [[ -v RESTORE ]]; then
    chmod -w "$file"
fi