#! /usr/bin/env bash

set -u

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."
declare -r YAD_CMD="$BASE_DIR/utils/yad"
source "$BASE_DIR/utils/yad_old_values.sh"
source "$BASE_DIR/utils/selector_filters.sh"

while getopts "o:" opt; do
    case $opt in
        o ) 
			declare -r OLD_VALUES_FILE=$(readlink -f "$OPTARG")
            ! test -e "$OLD_VALUES_FILE" && touch "$OLD_VALUES_FILE";;
	esac
done
shift $(expr $OPTIND - 1 )


declare -r SEARCH_DIR_OPTION="$(readlink -e "${1+$1}")"
declare -r EXTENSIONS_DEFAULT="ORF CRW CR2 RAW JPG"
# TODO photonumber tail should allow ranges
# TODO time of day should allow ranges
# TODO add more spacing between fields
options_string=$("$YAD_CMD" \
    --title="Select photos matching:" \
    --form \
    --field="Album:CBE" "$(old_values_or_default "$OLD_VALUES_FILE" "album" "")" \
    --field="Photo title:CBE" "$(old_values_or_default "$OLD_VALUES_FILE" "title" "")" \
    --field="Year:CBE" "$(old_values_or_default "$OLD_VALUES_FILE" "year" "$(date +%Y)")" \
    --field="Month:CB" "$(old_value_preselected_in_list "$OLD_VALUES_FILE" "month" "$MONTHS_INCL_EMPTY_VALUE")" \
    --field="Day of month:CB" "$(old_value_preselected_in_list "$OLD_VALUES_FILE" "dayofmonth" "$DAYS_OF_MONTH_INCL_EMPTY_VALUE")" \
    --field="Time of day:TEXT" "" \
    --field="Photo number ends with:TEXT" "" \
    --field="Search directory:DIR" "$SEARCH_DIR_OPTION" \
    --field="Allowed extensions:TEXT" "$EXTENSIONS_DEFAULT" 2> /dev/null)
yad_rc=$?
if [[ $yad_rc = 252 ]] || [[ $yad_rc = 1 ]]; then
    exit
fi

declare -r ALBUM=$(echo "$options_string" | cut -d'|' -f 1 | tr ' ' '-')
declare -r TITLE=$(echo "$options_string" | cut -d'|' -f 2 | tr ' ' '-')
declare -r YEAR=$(echo "$options_string" | cut -d'|' -f 3)
declare -r MONTH=$(echo "$options_string" | cut -d'|' -f 4)
declare -r DAY_OF_MONTH=$(echo "$options_string" | cut -d'|' -f 5)
declare -r TIME_OF_DAY=$(echo "$options_string" | cut -d'|' -f 6)
declare -r PHOTO_NUMBER_TAIL=$(echo "$options_string" | cut -d'|' -f 7)
# FIXME ensure that at least album or title and year have been defined
# FIXME handle missing SEARCH_DIR - if there is a way not to select one
#   MAYBE: check if yad passes the current dir as the default if no own default is set - if yes, we could check if entered
#   directory is current. con: what if user wants to save in current?
declare -r SEARCH_DIR=$(echo "$options_string" | cut -d'|' -f 8)
declare -r EXTENSIONS=$(echo "$options_string" | cut -d'|' -f 9)


if [[ -v OLD_VALUES_FILE ]]; then
    test -n "$ALBUM" && save_cb_value "$OLD_VALUES_FILE" "album" "$ALBUM" 5
    test -n "$TITLE" && save_cb_value "$OLD_VALUES_FILE" "title" "$TITLE" 10
    test -n "$YEAR" && save_cb_value "$OLD_VALUES_FILE" "year" "$YEAR" 5
    test -n "$MONTH" && save_single_value "$OLD_VALUES_FILE" "month" "$MONTH"
    test -n "$DAY_OF_MONTH" && save_single_value "$OLD_VALUES_FILE" "dayofmonth" "$DAY_OF_MONTH"
fi

year_dir_glob=$(year_glob $YEAR)
album_dir_glob=$(album_glob "$ALBUM")
day_dir_glob=$(date_path_glob "$YEAR" "$MONTH" "$DAY_OF_MONTH")
filename_glob=$(filename_glob "$TITLE" "$YEAR" "$MONTH" "$DAY_OF_MONTH" "$TIME_OF_DAY" "$PHOTO_NUMBER_TAIL")

find "$SEARCH_DIR" -regextype posix-extended -type f \
    -ipath "*/$year_dir_glob/$album_dir_glob/$day_dir_glob/$filename_glob.???" \
    -iregex ".+\.($(extensions_regex_alternatives))"