#! /usr/bin/env bash

set -u

declare -r APP_TITLE="Photo selector"

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."
declare -r POPUP_CMD="$BASE_DIR/utils/notification"
declare -r YAD_CMD="$BASE_DIR/utils/yad"
source "$BASE_DIR/utils/yad_old_values.sh"
source "$BASE_DIR/utils/selector_filters.sh"

while getopts "o:" opt; do
    case $opt in
        o ) 
			declare -r OLD_VALUES_FILE=$(readlink -f "$OPTARG")
            ! test -e "$OLD_VALUES_FILE" && touch "$OLD_VALUES_FILE";;
	esac
done
shift $(expr $OPTIND - 1 )


declare -r SEARCH_DIR="$(readlink -e "${1+$1}")"
if [[ -z $SEARCH_DIR ]]; then
    "$POPUP_CMD" -e "$APP_TITLE" "Cannot run selector without a search directory"
    exit 1
fi

declare -r EXTENSIONS_DEFAULT="ORF CRW CR2 RAW JPG"
# TODO photonumber tail should allow ranges
# TODO time of day should allow ranges
options_string=$("$YAD_CMD" \
    --title="Select photos from $SEARCH_DIR matching:" \
    --form \
    --field="Album:CBE" "$(old_values_or_default "$OLD_VALUES_FILE" "album" "")" \
    --field="Photo title:CBE" "$(old_values_or_default "$OLD_VALUES_FILE" "title" "")" \
    --field="Year:CBE" "$(old_values_or_default "$OLD_VALUES_FILE" "year" "$(date +%Y)")" \
    --field="Month:CB" "$(old_value_preselected_in_list "$OLD_VALUES_FILE" "month" "$MONTHS_INCL_EMPTY_VALUE")" \
    --field="Day of month:CB" "$(old_value_preselected_in_list "$OLD_VALUES_FILE" "dayofmonth" "$DAYS_OF_MONTH_INCL_EMPTY_VALUE")" \
    --field="Time of day:TEXT" "" \
    --field="Photo number ends with:TEXT" "" 2> /dev/null)
yad_rc=$?
if [[ $yad_rc = 252 ]] || [[ $yad_rc = 1 ]]; then
    exit
fi

declare -r ALBUM=$(echo "$options_string" | cut -d'|' -f 1 | tr ' ' '-')
declare -r TITLE=$(echo "$options_string" | cut -d'|' -f 2 | tr ' ' '-')
declare -r YEAR=$(echo "$options_string" | cut -d'|' -f 3)
declare -r MONTH=$(echo "$options_string" | cut -d'|' -f 4)
declare -r DAY_OF_MONTH=$(echo "$options_string" | cut -d'|' -f 5)
declare -r TIME_OF_DAY=$(echo "$options_string" | cut -d'|' -f 6)
declare -r PHOTO_NUMBER_TAIL=$(echo "$options_string" | cut -d'|' -f 7)

if [[ -z $ALBUM ]] && [[ -z $TITLE ]]; then
    "$POPUP_CMD" -e "$APP_TITLE" "One of album or title must be defined"
    exit 1
fi


if [[ -v OLD_VALUES_FILE ]]; then
    save_cb_value "$OLD_VALUES_FILE" "album" "$ALBUM" 25
    save_cb_value "$OLD_VALUES_FILE" "title" "$TITLE" 25
    # to prevent accidential gigantic result lists, never save the empty year value, that parameter should only be left out
    # if required
    test -n "$YEAR" && save_cb_value "$OLD_VALUES_FILE" "year" "$YEAR" 5
    save_single_value "$OLD_VALUES_FILE" "month" "$MONTH"
    save_single_value "$OLD_VALUES_FILE" "dayofmonth" "$DAY_OF_MONTH"
fi

year_dir_glob=$(year_glob $YEAR)
album_dir_glob=$(album_glob "$ALBUM")
day_dir_glob=$(date_path_glob "$YEAR" "$MONTH" "$DAY_OF_MONTH")
filename_glob=$(filename_glob "$TITLE" "$YEAR" "$MONTH" "$DAY_OF_MONTH" "$TIME_OF_DAY" "$PHOTO_NUMBER_TAIL")

find "$SEARCH_DIR" -regextype posix-extended -type f \
    -ipath "*/$year_dir_glob/$album_dir_glob/$day_dir_glob/$filename_glob.???" \
    -iregex ".+\.(ORF|RAW|JPG|CRW|CR2)"