#! /usr/bin/env bash

set -eu

declare -r APP_DIR=$(readlink -m "$HOME/.local/share/photo-scripts/")

export PATH="$APP_DIR:$PATH"

while getopts "p:c:q:" opt; do
    case $opt in
        c )
            # 1-100
            declare -r JPEG_COMPRESSION=$OPTARG;;
        q )
            # 1-3
            declare -r JPEG_QUALITY=$OPTARG;;
        p ) 
            declare -r PROFILES=$OPTARG;;
	esac
done
shift $(expr $OPTIND - 1 )

declare -r SOURCE=$(readlink -m "$1")
if ! [[ -e $SOURCE ]] && ! [[ -f $SOURCE ]]; then
    echo "[ERROR] Source file $SOURCE does not exist"
    exit 1
fi

if [[ $# = 2 ]]; then
    declare -r TARGET=$(readlink -m "$2")
fi


next_variant() {
    local -r source_photoid=$1
    local -r targetdir=$2

    local -r existing=$(find "$targetdir" -type f -name "$source_photoid*.jpg")

    if [[ -z $existing ]]; then
        # we need this branch, otherwise the next one would match, too (because there is always one line)
        # TBD would echo -n work? or use a here string?
        echo
    elif [[ $(echo "$existing" | wc -l) = 1 ]]; then
        if [[ $existing =~ .+-([0-9])+\..+ ]]; then
            echo $((${BASH_REMATCH[1]} + 1))
        else 
            echo "1"
        fi
    else    
        # FIXME TBD why must grep have "-v"?!
        local -r highest_variant=$(grep -v "$source_photoid-*.jpg" <<<"$existing" | sort | tail -n 1)   
        [[ $highest_variant =~ .+-([0-9])+\..+ ]]
        echo $((${BASH_REMATCH[1]} + 1))
    fi
}

compute_targetfile() {
    local -r source_filename=$(basename "$1")
    local -r targetdir=$2
    local -r photoid=${source_filename%%.*} 
    local -r next_variant=$(next_variant "$photoid" "$targetdir")
    # actually, we don't need to add the extension, Rawtherapee will select the correct one
    if [[ -n $next_variant ]]; then
        echo "$targetdir/$photoid-$next_variant.jpg"
    else 
        echo "$targetdir/$photoid.jpg"
    fi    
}

target_is_directory() {
    local -r target=$1
    ! [[ $target =~ .+\..+ ]]
}

if ! [[ -v TARGET ]]; then
    sourcedir=$(dirname "$SOURCE")
    targetdir="$sourcedir/converted"
    test -e "$targetdir" || mkdir "$targetdir"
    declare -r TARGETFILE=$(compute_targetfile "$SOURCE" "$targetdir")
elif target_is_directory "$TARGET"; then
    test -e "$TARGET" || mkdir "$TARGET"
    declare -r TARGETFILE=$(compute_targetfile "$SOURCE" "$TARGET")
else 
    declare -r TARGETFILE="$TARGET"
fi


# "-c" is not a real option but rather a marker, "only input files/dirs after this" - that's why all other options must go
# before that marker
rawtherapee --cli -s -O "$TARGETFILE" -c "$SOURCE"
# rt_out=$(rawtherapee --cli -s -O "$TARGETFILE" -c "$SOURCE" 2>&1)
# rt_rc=$?
# if [[ $rt_rc != 0 ]]; then
#     echo "[ERROR] Failed running RawTherapee, return code was $rt_rc" >&2
#     exit 1
# fi
