#! /usr/bin/env bash

set -eux

gpxfile=$1
offset_hours=$2

updated_gpxfile=$(mktemp)
cat "$gpxfile" > "$updated_gpxfile"

sed -n 's|.*<time>\([0-9-]*T[0-9:]*\.[0-9]*\)Z</time>.*|\1|p' "$gpxfile" | head -n 1 | while read -r zuluts; do 
    # TODO explain why we need to fake the timezone AND add hours on top
    localdate=$(date --iso-8601=seconds -d "$zuluts+0$offset_hours:00 +${offset_hours}hours")
    sed -i "s|$zuluts|$localdate|" "$updated_gpxfile"
done

less "$updated_gpxfile"

rm -f "$updated_gpxfile"