#! /usr/bin/env bash

set -eu

jpg_file=$1

geotag_files_searchdir="$(dirname "$jpg_file")/.."

geotag_file=$(find "$geotag_files_searchdir" -type f -iname "*.gpx" | head -n 1)
if [[ -z $geotag_file ]]; then
    echo "[WARN] No gpx geotag file(s) found in $geotag_files_searchdir" >&2
    exit
fi

exiftool -overwrite_original -geotag "$geotag_file" "$jpg_file" 