#! /usr/bin/env bash

set -eu

imported_files=$(</dev/stdin)
# yes, SECONDS will not cover the complete duration of all actions. but this action 
# is started already in parallel with all other pipeline actions. therefore it will 
# be approximately fine.
echo "[INFO] Imported $(wc -l <<<"$imported_files") files in $SECONDS seconds" >&2    
