#! /usr/bin/env bash

set -ue

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/../.."
source "$BASE_DIR/lib/strings.sh"
source "$BASE_DIR/lib/jpeg_iptc.sh"
source "$BASE_DIR/rawtherapee/lib/sidecar.sh"

album=$1

while read -r file; do

    if [[ $file =~ .+/converted/.+\.jpg ]]; then
        jpeg_add_iptc_keywords "$file" "$album"
    elif [[ $file =~ .+\.pp[23] ]]; then
        sidecar_add_iptc_keywords "$file" "$album"
    fi

    echo "$file"

done < /dev/stdin