#! /usr/bin/env bash

set -u

declare -r APP_TITLE="Archive processed photos"

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."

source "$BASE_DIR/lib/photofiles.sh"
source "$BASE_DIR/apps/lib/yad.sh"
source "$BASE_DIR/apps/lib/yad_form_values.sh"
source "$BASE_DIR/apps/lib/notification.sh"
source "$BASE_DIR/apps/lib/search_dirs.sh"

PATH="$BASE_DIR:$PATH"

declare -r SEARCH_DIRECTORIES_FILE="$HOME/.local/share/photo-scripts/archivable_directories"

declare -r ARCHIVE_DIR=$(readlink -e "${1+$1}")
if [[ -z $ARCHIVE_DIR ]]; then
    notify_error "$APP_TITLE" "No archive directory given or does not exist"
    exit 1
fi

if [[ -v 2 ]]; then

    search_dir=$2
    search_directories_value=$search_dir

else

    if ! [[ -e $SEARCH_DIRECTORIES_FILE ]]; then
        notify_error "$APP_TITLE" "Search directories file $SEARCH_DIRECTORIES_FILE does not exist"
        exit 1
    fi

    search_directories_value=$(get_search_directories_as_yad_option_keys "$SEARCH_DIRECTORIES_FILE")
fi

dialog_text="Select which photos to archive:"

album_values=$(remember_list "album" "b")
current_year=$(date +%Y)
year_values=$(remember_list "year" "gn" "$current_year")
month_values=$(prepare_list "$MONTHS" "gb" "$(remember_value "month")")

options_string=$(run_yad "$APP_TITLE" "$dialog_text" \
    --form \
    --field="search directory:CB" "$search_directories_value" \
    --field="Album:CBE" "$album_values" \
    --field="Year:CBE" "$year_values" \
    --field="Month:CB" "$month_values" )
yad_rc=$?
if [[ $yad_rc = 252 ]] || [[ $yad_rc = 1 ]]; then
    exit
fi

if [[ -z $search_dir ]]; then
    search_dir_key=$(get_option_at_index "$options_string" 1)
    search_dir=$(lookup_search_directory_from_option_key "$SEARCH_DIRECTORIES_FILE" "$search_dir_key")
fi

album=$(get_option_at_index "$options_string" 2)
year=$(get_option_at_index "$options_string" 3)
month=$(get_option_at_index "$options_string" 4)

memorize_form_combobox_values "$MEMORIZED_FORM_VALUES_FILE" "album" "$album" 5
memorize_form_combobox_values "$MEMORIZED_FORM_VALUES_FILE" "year" "$year" 5
memorize_form_value "$MEMORIZED_FORM_VALUES_FILE" "month" "$month"

archivable_photos=$(collect_archivable_photos \
    ${album:+-a "$album"} ${year:+-y "$year"} \
    ${month:+-m "$(month_value_from_name "$month")"} \
    "$search_dir")

if [[ -z $archivable_photos ]]; then
    notify_warning "$APP_TITLE" "No archivable photos found that match the filter"
    exit 1
fi

run_yad_selector_result_action_dialog "$APP_TITLE" \
    "$archivable_photos" "Archive the selected photos?"
yad_rc=$?
if [[ $yad_rc = 252 ]] || [[ $yad_rc = 1 ]]; then
    exit
fi

archive_photos "$ARCHIVE_DIR" <<<"$archivable_photos"
archive_photos_rc=$?
if [[ $archive_photos_rc = 0 ]]; then
    notify_info "$APP_TITLE" "Archived $(wc -l <<<"$archivable_photos") photo(s) to \"$ARCHIVE_DIR\""
else
    notify_error "$APP_TITLE" \
        "Archiving $(wc -l <<<"$archivable_photos") photo(s) to \"$ARCHIVE_DIR\" failed with return code $archive_photos_rc"
    exit 1
fi