#! /usr/bin/env bash

set -eu

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."
PATH="$BASE_DIR/apps:$BASE_DIR/rawtherapee/profile-builder:$PATH"

source "$BASE_DIR/apps/lib/notification.sh"
source "$BASE_DIR/lib/strings.sh"

sidecar_template_dir=$1
photographer=$2

selector | xargs create_sidecar -o -c "$photographer" "$sidecar_template_dir"  

notify_info "Creating RawTherapee sidecars" "Done"