#! /usr/bin/env bash

set -u

declare -r -x APP_TITLE="IPTC description editor"

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."

source "$BASE_DIR/apps/lib/yad.sh"
source "$BASE_DIR/apps/lib/yad_form_values.sh"
source "$BASE_DIR/apps/lib/notification.sh"
source "$BASE_DIR/lib/photofiles.sh"

PATH="$BASE_DIR:$BASE_DIR/apps:$PATH"

if [[ $# > 0 ]]; then
    photos=$(tr " " "\n" <<<$*)
else
    photos=$(selector) 
    selector_rc=$? 
    if [[ $selector_rc == 101 ]]; then
        exit
    elif [[ -z $photos ]]; then
        notify_warning "$APP_TITLE" "No matching photos found"  
        exit 1
    fi
fi

dialog_text="Set description (overwrites old description)"
description_label="Description"
description=$(run_yad_selector_result_action_dialog \
    "$APP_TITLE" "$photos" "$dialog_text" \
    --form \
    --field="$description_label:TXT")
yad_rc=$?
if [[ $yad_rc = 252 ]] || [[ $yad_rc = 1 ]]; then
    exit
fi

description=$(get_option_at_index "$description" 1)
change_photo_description "$description" $photos
rc=$?
if [[ $rc != 0 ]]; then
    notify_error "$APP_TITLE" \
        "Changing description of $(echo "$photos" | wc -l) photo(s) failed: $rc"
    exit 1
fi