#! /usr/bin/env bash

set -u

declare -r -x APP_TITLE="Edit photo metadata"

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."

PATH="$BASE_DIR:$BASE_DIR/lib:$BASE_DIR/apps:$PATH"

source "$BASE_DIR/apps/lib/yad.sh"
source "$BASE_DIR/apps/lib/form_values.sh"
source "$BASE_DIR/apps/lib/notification.sh"

declare -r SEARCH_DIR=$(readlink -e "${1+$1}")


augment_user_keywords() {
    local keywords=$1

    if [[ -v ALBUM_AS_KEYWORD ]]; then
        keywords="${keywords:+$keywords;}$ALBUM"
    fi

    if [[ -v TITLE_AS_KEYWORD ]]; then
        keywords="${keywords:+$keywords;}$TITLE"
    fi

    echo "$keywords"
}

equals_TRUE() {
    local -r string=$1
    test -n "$string" && test "TRUE" = "$string"
}


photos=$(selector "$SEARCH_DIR")
if [[ -z $photos ]]; then
    notify_warning "$APP_TITLE" "No matching photos found"
    exit 1
fi

prepare_combobox_values() (
    set -o noglob

    local -r field_name=$1
    local -r default_value=""

    local -r memorized_values=$(get_memorized_values_or_default \
        "$MEMORIZED_FORM_VALUES_FILE" "$field_name" "$default_value")
    # we simply add the preselected blank without checking if there is another blank in the string, that's easier
    # TBD TODO maybe get_memorized_values_or_default should already filter blank entries?
    echo "^!$memorized_values"
)

dialog_text="Metadata (blank fields will not be changed):"
album_field_value="$(prepare_combobox_values "album")"
title_field_value="$(prepare_combobox_values "title")"
keywords_field_value="$(prepare_combobox_values "keywords")"

# TODO add option to remove old album and title from keywords
 
user_edit_params=$(
    run_yad_selector_result_action_dialog "$APP_TITLE" "$photos" "$SEARCH_DIR" "$dialog_text" \
        --form \
        --field="Album:CBE" "$album_field_value" \
        --field="Add album name as a keyword:CHK" "TRUE" \
        --field="Title:CBE" "$title_field_value" \
        --field="Add title as a keyword:CHK" "TRUE" \
        --field="Keywords (separated by \";\"):CBE" "$keywords_field_value" 
)
yad_rc=$?
if [[ $yad_rc = 252 ]] || [[ $yad_rc = 1 ]]; then
    exit
fi

trim_whitespace() (
    shopt -s extglob

    local string=$1 
    string="${string##*( )}"
    echo "${string%%*( )}"
)

declare -r ALBUM=$(trim_whitespace "$(echo "$user_edit_params" | cut -d'|' -f 1)")
if [[ -n $ALBUM ]]; then
    memorize_form_combobox_values "$MEMORIZED_FORM_VALUES_FILE" "album" "$ALBUM" 25
    equals_TRUE "$(echo "$user_edit_params" | cut -d'|' -f 2)" && declare -r ALBUM_AS_KEYWORD=
fi

declare -r TITLE=$(trim_whitespace "$(echo "$user_edit_params" | cut -d'|' -f 3)")
if [[ -n $TITLE ]]; then
    memorize_form_combobox_values "$MEMORIZED_FORM_VALUES_FILE" "title" "$TITLE" 25
    equals_TRUE "$(echo "$user_edit_params" | cut -d'|' -f 4)" && declare -r TITLE_AS_KEYWORD=
fi

declare -r USER_KEYWORDS=$(trim_whitespace "$(echo "$user_edit_params" | cut -d'|' -f 5)")
if [[ -n $USER_KEYWORDS ]]; then
    memorize_form_combobox_values "$MEMORIZED_FORM_VALUES_FILE" "keywords" "$USER_KEYWORDS" 25
fi
declare -r KEYWORDS=$(augment_user_keywords "$USER_KEYWORDS")

if [[ -n $KEYWORDS ]]; then
    add_keywords "$KEYWORDS" "$photos" > /dev/null # we're not interested in the printed files
    add_keywords_rc=$?
    if [[ $add_keywords_rc = 0 ]]; then
        notify_info "$APP_TITLE" "Added keywords \"$KEYWORDS\" to $(echo "$photos" | wc -l) photo(s)"
    else
        notify_error "$APP_TITLE" \
            "Failed adding keywords \"$KEYWORDS\" to $(echo "$photos" | wc -l) photo(s) with return code $add_keywords_rc"
        exit 1
    fi
fi

files=$photos

if [[ -n $TITLE ]]; then
    files=$(set_title "$TITLE" $files)
    rename_rc=$?
    if [[ $rename_rc = 0 ]]; then
        notify_info "$APP_TITLE" "Changing title of $(echo "$photos" | wc -l) photo(s) to \"$TITLE\" done"
    else
        notify_error "$APP_TITLE" \
            "Changing title of $(echo "$photos" | wc -l) photo(s) to \"$TITLE\" failed with return code $rename_rc"
        exit 1
    fi
fi

if [[ -n $ALBUM ]]; then
    # if we changed photo titles, $files will now also contain all associated files. But we can safely pass
    # $files to change_album because it will just throw away all irrelevant files
    change_album "$ALBUM" "$files"
    change_album_rc=$?
    if [[ $change_album_rc = 0 ]]; then
        notify_info "$APP_TITLE" "Moving $(echo "$photos" | wc -l) photos to \"$ALBUM\" done"
    else
        notify_error -e "$APP_TITLE" \
            "Moving $(echo "$photos" | wc -l) photos to \"$ALBUM\" failed with return code $change_album_rc"
        exit 1
    fi
elif [[ -n $TITLE ]] || [[ -n $KEYWORDS ]]; then 
    echo "$files"
fi