#! /usr/bin/env bash

set -u

declare -r -x APP_TITLE="IPTC keyword editor"

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."

source "$BASE_DIR/apps/lib/yad.sh"
source "$BASE_DIR/apps/lib/yad_form_values.sh"
source "$BASE_DIR/apps/lib/notification.sh"
source "$BASE_DIR/lib/photofiles.sh"
source "$BASE_DIR/lib/strings.sh"

PATH="$BASE_DIR/metadata:$BASE_DIR:$BASE_DIR/apps:$PATH"

if [[ $# > 0 ]]; then
    photos=$(tr " " "\n" <<<$*)
else
    photos=$(selector) 
    selector_rc=$? 
    if [[ $selector_rc == 101 ]]; then
        exit
    elif [[ -z $photos ]]; then
        notify_warning "$APP_TITLE" "No matching photos found"  
        exit 1
    fi    
fi

dialog_text="List keywords to update separated \";\". To remove a keyword, prepend with  \"-\". No quoting required"
keywords_label="Keywords"
keywords_value=$(remember_list "keywords" "gn")
edit_keywords_params=$(run_yad_selector_result_action_dialog \
    "$APP_TITLE" "$photos" "$dialog_text" --form \
    --field="$keywords_label:CBE" "$keywords_value")
yad_rc=$?
if [[ $yad_rc = 252 ]] || [[ $yad_rc = 1 ]]; then
    exit
fi

keywords=$(get_option_at_index "$edit_keywords_params" 1)
if [[ -z $keywords ]]; then    
    notify_warning "$APP_TITLE" "At least one keyword is required"  
    exit 1
fi
memorize_form_combobox_values "$MEMORIZED_FORM_VALUES_FILE" "keywords" "$keywords" 25

change_photo_keywords "$keywords" "$photos"
update_keywords_rc=$?
if [[ $update_keywords_rc = 0 ]]; then
    notify_info "$APP_TITLE" "Updated keywords \"$keywords\" in $(wc -l <<<"$photos") photo(s)"
else
    notify_error "$APP_TITLE" \
        "Failed to update keywords \"$keywords\" int $(wc -l <<<"$photos") photo(s): $update_keywords_rc"
    exit 1
fi