#! /usr/bin/env bash

set -u

declare -r APP_TITLE="Import photos"

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."

source "$BASE_DIR/lib/strings.sh"
source "$BASE_DIR/apps/lib/yad.sh"
source "$BASE_DIR/apps/lib/yad_form_values.sh"
source "$BASE_DIR/apps/lib/notification.sh"

PATH="$BASE_DIR:$BASE_DIR/rawtherapee/profile-builder:$PATH"


while getopts "c:" opt; do
    case $opt in
        c ) 
			declare -r CREATOR_OPTION=$OPTARG;;
	esac
done
shift $(expr $OPTIND - 1 )


declare -r DCIM_DIR=${1+$1}
declare -r TARGET_DIR=${2+$2}
declare -r SIDECAR_TEMPLATES_DIR=${3+$3}

remove_wildcard_entries() (
    local -r entries=$1

    IFS='!'

    for entry in $entries; do
        if ! [[ $entry =~ .*\*.*|.*\?.* ]]; then
            echo "$entry"
        fi
    done | paste -s -d '!' -
)

declare -r DEFAULT_ALBUM_VALUE="New photos"
declare -r DEFAULT_TITLE_VALUE=""

dialog_txt="Import photos from $DCIM_DIR to $TARGET_DIR"

album_cb_values=$(remember_list "album" "gn" "$DEFAULT_ALBUM_VALUE")
if [[ -z $album_cb_values ]]; then
    album_cb_values=$DEFAULT_ALBUM_VALUE
fi
title_cb_values=$(remember_list "title" "gn" "$DEFAULT_TITLE_VALUE")
if [[ -z $title_cb_values ]]; then
    title_cb_values=$DEFAULT_TITLE_VALUE
fi    
creator_value=${CREATOR_OPTION+$CREATOR_OPTION}
keywords_cb_values=$(remember_list "keywords" "gn")

# TODO use textfield for creator if CREATOR_OPTION is set, otherwise use memorized values in CBE
# afterwards: if CREATOR_OPTION is set, fetch memorized values and combine with CREATOR_OPTION (set as selected entry)
# TODO add option to add album + title as keywords
#   don't do it if user entered no values and we are using "New photos"
options_string=$(run_yad "$APP_TITLE" "$dialog_txt" \
    --form \
    --field="Album:CBE" "$album_cb_values" \
    --field="Photo title:CBE" "$title_cb_values" \
    --field="Photographer/creator" "$creator_value" \
    --field="Keywords (separated by \";\"):CBE" "$keywords_cb_values")
yad_rc=$?
if [[ $yad_rc = 252 ]] || [[ $yad_rc = 1 ]]; then
    exit
fi

album_string=$(trim_whitespace "$(get_option_at_index "$options_string" 1)")
if [[ -n $album_string ]]; then
    declare -r ALBUM=$album_string
    memorize_form_combobox_values "$MEMORIZED_FORM_VALUES_FILE" "album" "$ALBUM" 25
else 
    declare -r ALBUM="New photos"
fi

title_string=$(trim_whitespace "$(get_option_at_index "$options_string" 2)")
test -n "$title_string" && declare -r TITLE="$title_string" && \
    memorize_form_combobox_values "$MEMORIZED_FORM_VALUES_FILE" "title" "$TITLE" 25

creator_string=$(trim_whitespace "$(get_option_at_index "$options_string" 3)")
test -n "$creator_string" && declare -r CREATOR=$creator_string 
# TODO memorize creator

keywords_string=$(trim_whitespace "$(get_option_at_index "$options_string" 4)")
test -n "$keywords_string" && declare -r KEYWORDS=$keywords_string && \
    memorize_form_combobox_values "$MEMORIZED_FORM_VALUES_FILE" "keywords" "$KEYWORDS" 25


imported_photos=$(import_photos ${ALBUM+-a "$ALBUM"} ${TITLE+-t "$TITLE"} "$DCIM_DIR" "$TARGET_DIR")
import_photos_rc=$?
if [[ $import_photos_rc = 0 ]]; then
    imported_photos_count=$(echo "$imported_photos" | wc -l)
    notify_info "$APP_TITLE" "Imported $imported_photos_count photo(s)"
else
    notify_error "$APP_TITLE" "Importing photos from $DCIM_DIR failed with return code $import_photos_rc"
    exit 1
fi

created_sidecars=$(create_sidecar ${CREATOR+-c "$CREATOR"} ${KEYWORDS+-k "$KEYWORDS"} "$SIDECAR_TEMPLATES_DIR" \
    $(echo $imported_photos))
create_sidecar_rc=$?
if [[ $create_sidecar_rc = 0 ]]; then
    sidecars_count=$(echo "$created_sidecars" | wc -l)
    notify_info "$APP_TITLE" "Created $sidecars_count sidecar(s)"
else
    notify_error "$APP_TITLE" "Creating sidecars failed with return code $create_sidecar_rc"
    exit 1
fi

total_size_mb=$(du -ch $imported_photos | tail -1 | cut -f 1)
duration_in_minutes=$(( $SECONDS / 60 ))
notify_info -i "$APP_TITLE" \
    "Imported $imported_photos_count photo(s) ($total_size_mb MB) in $duration_in_minutes minutes."