#! /usr/bin/env bash

set -u

declare -r APP_TITLE="Import photos"

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."

declare -r IMPORT_CMD="$BASE_DIR/import_photos"
declare -r CREATE_SIDECAR_CMD="$BASE_DIR/profile-builder/create_sidecar"
source "$BASE_DIR/apps/lib/yad.sh"
source "$BASE_DIR/apps/lib/form_values.sh"
source "$BASE_DIR/apps/lib/notification.sh"


while getopts "c:" opt; do
    case $opt in
        c ) 
			declare -r CREATOR_OPTION=$OPTARG;;
	esac
done
shift $(expr $OPTIND - 1 )


declare -r DCIM_DIR=${1+$1}
declare -r TARGET_DIR=${2+$2}
declare -r SIDECAR_TEMPLATES_DIR=${3+$3}

# TODO use textfield for creator if CREATOR_OPTION is set, otherwise use memorized values in CBE
# afterwards: if CREATOR_OPTION is set, fetch memorized values and combine with CREATOR_OPTION (set as selected entry)
options_string=$(run_yad "$APP_TITLE" "Import photos from $DCIM_DIR to $TARGET_DIR" \
    --form \
    --field="Album:CBE" "$(get_memorized_values_or_default "$MEMORIZED_FORM_VALUES_FILE" "album" "New photos")" \
    --field="Photo title:CBE" "$(get_memorized_values_or_default "$MEMORIZED_FORM_VALUES_FILE" "title" "")" \
    --field="Photographer/creator" "${CREATOR_OPTION+$CREATOR_OPTION}" \
    --field="Keywords (separated by \";\"):CBE" "$(get_memorized_values_or_default "$MEMORIZED_FORM_VALUES_FILE" "keywords" "")")
yad_rc=$?
if [[ $yad_rc = 252 ]] || [[ $yad_rc = 1 ]]; then
    exit
fi

declare -r ALBUM="$(echo "$options_string" | cut -d'|' -f 1 | tr ' ' '-')"
memorize_form_combobox_values "$MEMORIZED_FORM_VALUES_FILE" "album" "$ALBUM" 25

title_string="$(echo "$options_string" | cut -d'|' -f 2 | tr ' ' '-')"
test -n "$title_string" && declare -r TITLE="$title_string" && \
    memorize_form_combobox_values "$MEMORIZED_FORM_VALUES_FILE" "title" "$TITLE" 25

creator_string="$(echo "$options_string" | cut -d'|' -f 3)"
test -n "$creator_string" && declare -r CREATOR=$creator_string 
# TODO memorize creator

keywords_string="$(echo "$options_string" | cut -d'|' -f 4)"
test -n "$keywords_string" && declare -r KEYWORDS=$keywords_string && \
    memorize_form_combobox_values "$MEMORIZED_FORM_VALUES_FILE" "keywords" "$KEYWORDS" 25


imported_photos=$("$IMPORT_CMD" ${ALBUM+-a "$ALBUM"} ${TITLE+-t "$TITLE"} "$DCIM_DIR" "$TARGET_DIR")
import_photos_rc=$?
if [[ $import_photos_rc = 0 ]]; then
    imported_photos_count=$(echo "$imported_photos" | wc -l)
    notify_info "$APP_TITLE" "Imported $imported_photos_count photo(s)"
else
    notify_error "$APP_TITLE" "Importing photos from $DCIM_DIR failed with return code $import_photos_rc"
    exit 1
fi

created_sidecars=$("$CREATE_SIDECAR_CMD" ${CREATOR+-c "$CREATOR"} ${KEYWORDS+-k "$KEYWORDS"} "$SIDECAR_TEMPLATES_DIR" \
    $(echo $imported_photos))
create_sidecar_rc=$?
if [[ $create_sidecar_rc = 0 ]]; then
    sidecars_count=$(echo "$created_sidecars" | wc -l)
    notify_info "$APP_TITLE" "Created $sidecars_count sidecar(s)"
else
    notify_error "$APP_TITLE" "Creating sidecars failed with return code $create_sidecar_rc"
    exit 1
fi

total_size_mb=$(du -ch $imported_photos | tail -1 | cut -f 1)
duration_in_minutes=$(( $SECONDS / 60 ))
notify_info -i "$APP_TITLE" \
    "Imported $imported_photos_count photo(s) ($total_size_mb MB) in $duration_in_minutes minutes."