#! /usr/bin/env bash

declare -r -x APP_TITLE="IPTC keyword editor"

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."

declare -r SELECTOR="$BASE_DIR/apps/selector"
declare -r POPUP_CMD="$BASE_DIR/utils/notification"
declare -r YAD_CMD="$BASE_DIR/utils/yad"
source "$BASE_DIR/utils/yad_old_values.sh"
declare -r SET_KEYWORDS_CMD="$BASE_DIR/set_iptc_keywords"
source "$BASE_DIR/utils/yad.sh"

declare -r OLD_VALUES_FILE="$(get_old_values_file "selector")"
declare -r SEARCH_DIR=$(readlink -e "${1+$1}")


photos=$("$SELECTOR" "$SEARCH_DIR") 
if [[ -z $photos ]]; then
    "$POPUP_CMD" -w "$APP_TITLE" "No matching photos found"  
    exit 1
fi

set_iptc_params=$(run_yad_selector_result_action_dialog "$APP_TITLE" "$photos" "$SEARCH_DIR" "" \
    --form \
    --field="Add keyword(s) (separated by \";\"):CBE" "$(old_values_or_default "$OLD_VALUES_FILE" "keywords" "")" )
yad_rc=$?
if [[ $yad_rc = 252 ]] || [[ $yad_rc = 1 ]]; then
    exit
fi

declare -r KEYWORDS=$(echo "$set_iptc_params" | cut -d'|' -f 1 | tr ' ' '-')
if [[ -z $KEYWORDS ]]; then    
    "$POPUP_CMD" -e "$APP_TITLE" "At least one keyword is required"  
    exit 1
fi

"$SET_KEYWORDS_CMD" "$KEYWORDS" "$photos"
set_keywords_rc=$?
if [[ $set_keywords_rc = 0 ]]; then
    "$POPUP_CMD" -i "$APP_TITLE" "Adding IPTC keywords \"$KEYWORDS\" of $(echo "$photos" | wc -l) photo(s) done"
else
    "$POPUP_CMD" -w "$APP_TITLE" \
        "Adding IPTC keywords \"$KEYWORDS\" of $(echo "$photos" | wc -l) photo(s) failed with return code $set_keywords_rc"
    exit 1
fi

