#! /usr/bin/env bash

declare -r APP_TITLE="IPTC keyword editor"

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."

declare -r SELECTOR="$BASE_DIR/utils/selector"
declare -r POPUP_CMD="$BASE_DIR/utils/notification"
declare -r YAD_CMD="$BASE_DIR/utils/yad"
source "$BASE_DIR/utils/yad_helpers.sh"
declare -r SET_KEYWORDS_CMD="$BASE_DIR/set_iptc_keywords"

declare -r OLD_VALUES_FILE="$(get_old_values_file "selector")"
declare -r SEARCH_DIR=$(readlink -e "${1+$1}")


photos=$("$SELECTOR" -o "$OLD_VALUES_FILE" "$SEARCH_DIR") 
if [[ -z $photos ]]; then
    "$POPUP_CMD" -w "$APP_TITLE" "No matching photos found"  
    exit 1
fi

remove_searchdir_from_photos_list()  {
    local -r list=$1

    echo "$list" | while read -r photo; do 
        echo ${photo#$SEARCH_DIR/}
    done
}    

dialog_text=$(echo -e "Edit IPTC keywords of listed photos\n$(remove_searchdir_from_photos_list "$photos")\n\n")
set_iptc_params=$("$YAD_CMD" \
    --title="$APP_TITLE" \
    --text="$dialog_text" \
    --form \
    --field="Keywords (separated by \";\"):CBE" "$(old_values_or_default "$OLD_VALUES_FILE" "keywords" "")" )
yad_rc=$?
if [[ $yad_rc = 252 ]] || [[ $yad_rc = 1 ]]; then
    exit
fi

declare -r KEYWORDS=$(echo "$set_iptc_params" | cut -d'|' -f 1 | tr ' ' '-')
if [[ -z $KEYWORDS ]]; then    
    "$POPUP_CMD" -e "$APP_TITLE" "At least one keyword is required"  
    exit 1
fi

"$SET_KEYWORDS_CMD" "$KEYWORDS" "$photos"

