#! /usr/bin/env bash

set -u

declare -r APP_TITLE="Move photos"

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."

declare -r SELECTOR="$BASE_DIR/utils/selector"
declare -r MOVE_PHOTOS="$BASE_DIR/lib/move_photos.sh"
declare -r POPUP_CMD="$BASE_DIR/utils/notification"
declare -r YAD_CMD="$BASE_DIR/utils/yad"
source "$BASE_DIR/utils/yad_old_values.sh"

declare -r OLD_VALUES_FILE="$(get_old_values_file "selector")"
declare -r SEARCH_DIR=$(readlink -e "${1+$1}")


photos=$("$SELECTOR" -o "$OLD_VALUES_FILE" "$SEARCH_DIR") 
if [[ -z $photos ]]; then
    "$POPUP_CMD" -w "$APP_TITLE" "No matching photos found"  
    exit 1
fi

remove_searchdir_from_photos_list()  {
    local -r list=$1

    echo "$list" | while read -r photo; do 
        echo ${photo#$SEARCH_DIR/}
    done
}    

dialog_text=$(echo -e "Move listed photos\n$(remove_searchdir_from_photos_list "$photos")\nto a different album:\n\n")

move_to_album_params=$("$YAD_CMD" \
    --title="$APP_TITLE" \
    --text="$dialog_text" \
    --form \
    --field="New album (required):CBE" "$(old_values_or_default "$OLD_VALUES_FILE" "album" "")" \
    --field="Rename photos:CHK" "FALSE")
yad_rc=$?
if [[ $yad_rc = 252 ]] || [[ $yad_rc = 1 ]]; then
    exit
fi

declare -r TARGET_ALBUM_NAME=$(echo "$move_to_album_params" | cut -d'|' -f 1 | tr ' ' '-')
if [[ -z $TARGET_ALBUM_NAME ]]; then    
    "$POPUP_CMD" -e "$APP_TITLE" "New album name is required"  
    exit 1
fi

declare -r RENAME_PHOTOS_OPTION=$(echo "$move_to_album_params" | cut -d'|' -f 2)
if [[ $RENAME_PHOTOS_OPTION = "TRUE" ]]; then
    declare -r RENAME_MODE="b"
else 
    declare -r RENAME_MODE="a"
fi

"$MOVE_PHOTOS" -r "$TARGET_ALBUM_NAME" -m $RENAME_MODE "$photos"