#! /usr/bin/env bash

set -u

declare -r -x APP_TITLE="Move photos"

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."

PATH="$BASE_DIR/metadata:$BASE_DIR:$BASE_DIR/lib:$BASE_DIR/apps:$PATH"

source "$BASE_DIR/apps/lib/yad.sh"
source "$BASE_DIR/apps/lib/yad_form_values.sh"
source "$BASE_DIR/apps/lib/notification.sh"
source "$BASE_DIR/lib/photofiles.sh"

if [[ $# > 0 ]]; then
    photos=$(tr " " "\n" <<<$*)
else
    photos=$(selector) 
    selector_rc=$? 
    if [[ $selector_rc == 101 ]]; then
        exit
    elif [[ -z $photos ]]; then
        notify_warning "$APP_TITLE" "No matching photos found"  
        exit
    fi
fi

album_field_value=$(remember_list "album" "gnl")
move_params=$(run_yad_selector_result_action_dialog "$APP_TITLE" "$photos" "" \
    --form \
    --field="Move to album:CBE" "$album_field_value" \
    --field="Album name is added as keyword:CHK" "TRUE" \
    --field="Remove old album name from keywords:CHK" "FALSE" \
    --field="Photo titles are changed to album title:CHK" "FALSE")
yad_rc=$?
if [[ $yad_rc = 252 ]] || [[ $yad_rc = 1 ]]; then
    exit
fi

declare -r target_album_name=$(get_option_at_index "$move_params" 1)
if [[ -z $target_album_name ]]; then    
    notify_warning "$APP_TITLE" "New album name is required"  
    exit 1
fi
memorize_form_combobox_values "$MEMORIZED_FORM_VALUES_FILE" "album" "$target_album_name" 25

is_option_selected "$move_params" 2 && declare set_target_album_name_keyword=
is_option_selected "$move_params" 3 && declare remove_old_album_name_keyword=
is_option_selected "$move_params" 4 && declare change_photo_titles_to_album_name=

change_photo_album ${remove_old_album_name_keyword+-o} ${set_target_album_name_keyword+-a} \
    ${change_photo_titles_to_album_name+-t} "$target_album_name" "$photos"
rc=$?
if [[ $rc != 0 ]]; then
    notify_error "$APP_TITLE" \
        "Failed changing album of $(wc -l "$photos") photos to \"$target_album_name\": $change_album_rc"
    exit 1
fi

notify_info "$APP_TITLE" "Changed album of $(wc -l <<<"$photos") photos to \"$target_album_name\""