#! /usr/bin/env bash

set -u

declare -r -x APP_TITLE="Rename photos"

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."

source "$BASE_DIR/lib/strings.sh"
source "$BASE_DIR/apps/lib/yad.sh"
source "$BASE_DIR/apps/lib/yad_form_values.sh"
source "$BASE_DIR/apps/lib/notification.sh"
source "$BASE_DIR/lib/photofiles.sh"

PATH="$BASE_DIR/metadata:$BASE_DIR:$BASE_DIR/apps:$PATH"

if [[ $# > 0 ]]; then
    photos=$(tr " " "\n" <<<$*)
else
    photos=$(selector)
    selector_rc=$? 
    if [[ $selector_rc == 101 ]]; then
        exit
    elif [[ -z $photos ]]; then
        notify_warning "$APP_TITLE" "No matching photos found"
        exit 1
    fi
fi


title_field_values=$(remember_list "title" "gnl")
rename_params=$(run_yad_selector_result_action_dialog "$APP_TITLE" "$photos" "" \
    --form \
    --field="Change photo title(s) to:CBE" "$title_field_values" \
    --field="Allow case change only:CHK" "FALSE" \
    --field="Add title as a keyword:CHK" "TRUE" \
    --field="Remove old title keyword:CHK" "FALSE")
yad_rc=$?
if [[ $yad_rc = 252 ]] || [[ $yad_rc = 1 ]]; then
    exit
fi

declare -r new_title=$(trim_whitespace "$(get_option_at_index "$rename_params" 1)")
if [[ -z $new_title ]]; then    
    notify_warning "$APP_TITLE" "New photo title is required"  
    exit 1
fi
memorize_form_combobox_values "$MEMORIZED_FORM_VALUES_FILE" "title" "$new_title" 25
is_option_selected "$rename_params" 2 && declare allow_case_change="-c"
is_option_selected "$rename_params" 3 && declare add_title_as_keyword=
is_option_selected "$rename_params" 4 && declare remove_old_title_keyword=


if [[ -v remove_old_title_keyword ]]; then
    remove_keywords_title_entry $photos
    rc=$?
    if [[ $rc != 0 ]]; then
        notify_error "$APP_TITLE" \
            "Failed to remove old title keyword. Return code: $rc"
        exit 1
    fi
fi

if [[ -v add_title_as_keyword ]]; then
    add_keywords "$new_title" $photos
    rc=$?
    if [[ $rc != 0 ]]; then
        notify_error "$APP_TITLE" \
            "Failed adding title as keyword with return code $rc"
        exit 1
    fi
fi

rename ${allow_case_change-} "$new_title" $photos 
rc=$?
if [[ $rc != 0 ]]; then
    notify_error "$APP_TITLE" \
        "Changing title of $(echo "$photos" | wc -l) photo(s) to \"$new_title\" failed with return code $rc"
    exit 1
fi

notify_info "$APP_TITLE" "Changing title of $(echo "$photos" | wc -l) photo(s) to \"$new_title\" done"