#! /usr/bin/env bash

set -u

declare -r CANCELLED_RC=101

! test -v APP_TITLE && declare -r APP_TITLE="Photo selector"

declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."

source "$BASE_DIR/apps/lib/yad.sh"
source "$BASE_DIR/apps/lib/form_values.sh"
source "$BASE_DIR/apps/lib/find_globs_factory.sh"
source "$BASE_DIR/apps/lib/notification.sh"


declare -r SEARCH_DIR="$(readlink -e "${1+$1}")"
if [[ -z $SEARCH_DIR ]]; then
    notify_error "$APP_TITLE" "Cannot run selector without a search directory"
    exit 1
fi


album_form_value=$(get_memorized_values_or_default "$MEMORIZED_FORM_VALUES_FILE" "album" "")
title_form_value=$(get_memorized_values_or_default "$MEMORIZED_FORM_VALUES_FILE" "title" "")
year_form_value=$(get_memorized_values_or_default "$MEMORIZED_FORM_VALUES_FILE" "year" "$(date +%Y)")
month_form_value=$(get_memorized_value_preselected_in_all_values_list \
    "$MEMORIZED_FORM_VALUES_FILE" "month" "!$MONTHS")
dayofmonth_form_value=$(get_memorized_value_preselected_in_all_values_list \
    "$MEMORIZED_FORM_VALUES_FILE" "dayofmonth" "!$DAYS_OF_MONTH")

# TODO time of day should allow ranges
options_string=$(run_yad "$APP_TITLE" "Select photos from $SEARCH_DIR matching" \
    --form \
    --field="album name:CBE" "$album_form_value" \
    --field="photo title:CBE" "$title_form_value" \
    --field="year (4 digits):CBE" "$year_form_value" \
    --field="month:CB" "$month_form_value" \
    --field="day of month:CB" "$dayofmonth_form_value" \
    --field="time of day:TEXT" "" \
    --field="photo number ends with or is in range:TEXT" "" 2> /dev/null)
yad_rc=$?
if [[ $yad_rc = 252 ]] || [[ $yad_rc = 1 ]]; then
    exit $CANCELLED_RC
fi


declare -r ALBUM=$(cut -d'|' -f 1 <<<"$options_string")
declare -r TITLE=$(cut -d'|' -f 2 <<<"$options_string")
if [[ -z $ALBUM ]] && [[ -z $TITLE ]]; then
    notify_warning "$APP_TITLE" "One of album or title must be defined"
    exit 1
fi

declare -r YEAR=$(cut -d'|' -f 3 <<<"$options_string")
declare -r MONTH=$(cut -d'|' -f 4 <<<"$options_string")
declare -r DAY_OF_MONTH=$(cut -d'|' -f 5 <<<"$options_string")
declare -r TIME_OF_DAY=$(cut -d'|' -f 6 <<<"$options_string")

unpad_number() {
    local -r number_optional_zeropadded=$1
    echo "$((10#$number_optional_zeropadded))"
}

# if number_tail looks like a range (e.g. "2-17"), use an empty NUMBER_TAIL for find and set 
# NUMBER_TAIL_MIN/MAX and NUMBER_TAIL_SIZE. otherwise NUMBER_TAIL is set to number_tail
number_tail=$(echo "$options_string" | cut -d'|' -f 7)
if [[ $number_tail =~ [0-9]+-[0-9]+ ]]; then
    declare -r NUMBER_TAIL=""
    declare -r NUMBER_TAIL_MIN=$(unpad_number "$(echo "$number_tail" | cut -d'-' -f1)")
    declare -r NUMBER_TAIL_MAX=$(unpad_number "$(echo "$number_tail" | cut -d'-' -f2)")

    if (( $NUMBER_TAIL_MIN > "$NUMBER_TAIL_MAX" )); then
        notify_warning "$APP_TITLE" \
            "Lower bound $NUMBER_TAIL_MIN for number tail is larger than upper bound $NUMBER_TAIL_MAX"
        exit 1
    fi  

    # echo must not add a newline because that would count as an extra character
    declare -r NUMBER_TAIL_SIZE=$(echo -n "$NUMBER_TAIL_MAX" | wc -m)
else
    declare -r NUMBER_TAIL=$number_tail
fi


memorize_form_combobox_values "$MEMORIZED_FORM_VALUES_FILE" "album" "$ALBUM" 25
memorize_form_combobox_values "$MEMORIZED_FORM_VALUES_FILE" "title" "$TITLE" 25
# to prevent gigantic result lists by accident, never save the empty year value, that parameter 
# should only be left out if explicitely desired (i.e. user has to remove any year value from the field)
test -n "$YEAR" && memorize_form_combobox_values "$MEMORIZED_FORM_VALUES_FILE" "year" "$YEAR" 5
memorize_form_value "$MEMORIZED_FORM_VALUES_FILE" "month" "$MONTH"
memorize_form_value "$MEMORIZED_FORM_VALUES_FILE" "dayofmonth" "$DAY_OF_MONTH"


get_number_tail() {
    local -r photo_file=$1
    local -r tail_size=$2

    file_name=$(basename "$photo_file")
    file_name_no_ext=${file_name%.*}
    echo $(unpad_number "${file_name_no_ext: -$tail_size}")
}

year_dir_glob=$(year_glob $YEAR)
album_sanitized=$(tr ' ' '-' <<<"$ALBUM")
album_dir_glob=$(album_glob "$album_sanitized")
month_value=$(month_value_from_name "$MONTH")
day_dir_glob=$(date_path_glob "$YEAR" "$month_value" "$DAY_OF_MONTH")
title_sanitized=$(tr ' ' '-' <<<"$TITLE")
filename_glob=$(filename_glob "$title_sanitized" "$YEAR" "$month_value" "$DAY_OF_MONTH" "$TIME_OF_DAY" "$NUMBER_TAIL")

find "$SEARCH_DIR" -regextype posix-extended -type f \
        -ipath "*/$year_dir_glob/$album_dir_glob/$day_dir_glob/$filename_glob.???" \
        -iregex ".+\.(ORF|RAW|JPG|CRW|CR2)" ! -path "*/converted/*" | \
# run all found files through range checks but skip all checks if no ranges are in use
while read -r matched_file; do
    if [[ -v NUMBER_TAIL_MIN ]]; then 
        number_tail=$(get_number_tail "$matched_file" "$NUMBER_TAIL_SIZE")
        (( $NUMBER_TAIL_MIN <= $number_tail )) && (( $number_tail <= $NUMBER_TAIL_MAX )) && \
            echo "$matched_file"
    else 
        echo "$matched_file"
    fi
done | sort

