#! /usr/bin/env bash

set -u

declare -r APP_DIR=$(readlink -m "$HOME/.local/share/photo-scripts/")
declare -r BASEDIR="$(dirname "$(readlink -e "$0")")/../../"

source "$BASEDIR/lib/strings.sh"
source "$BASEDIR/lib/iptc.sh"
source "$BASEDIR/lib/jpeg_iptc.sh"
source "$BASEDIR/lib/photofiles.sh"
source "$BASEDIR/rawtherapee/lib/sidecar.sh"

export PATH="$(dirname $(readlink -f $0)):$PATH"

declare -r LOCK_FILE="$APP_DIR/rawtherapee_output_watcher.lock"

# NOTE postsaveprocessor is started alongside rawtherapee and should exit if rawtherapee is closed. however, this
# does not always work 100%. therefore, use a lockfile to prevent more than one running instance (to prevent 
# confusion and also because inotifywait )
if [[ -f $LOCK_FILE ]]; then
    echo "[WARN] Old lock file $LOCK_FILE exists, will try to kill old instance" >&2
    other_instance=$(cat $LOCK_FILE)
    kill $other_instance
    # NOTE wait 2 secs so that we have a chance to write into our own LOCK_FILE and not have it deleted by the other
    # instance (when that one tries to remove it on exit)
    sleep 2
fi
echo "$$" > $LOCK_FILE

cleanup() {
    # inotifywait with "-monitor" will not exit if this script is killed so it has to be killed separately
    pkill -f "inotifywait --monitor.*$WATCH_DIR.*"
    test -e "$LOCK_FILE" && rm $LOCK_FILE
}
trap cleanup EXIT

# TODO allow multiple watch dirs
declare -r WATCH_DIR="$(readlink -f $1)"
if [[ -z $WATCH_DIR ]]; then
	echo "[ERROR] Watched directory does not exist" >&2
	exit 1
fi

fix_variantfile_iptc() {
    local -r file=$1

    echo "[INFO] Fixing IPTC headline and caption of variant output file $file" >&2

    iptc_headline=$(iptc_headline_from_photofile "$file")
    iptc_caption=$(iptc_caption_from_photofile "$file")
    case "$new_file" in 
        *.pp3 )
            set -x
            sidecar_set_property "$file" "IPTC" "Headline" "$iptc_headline"
            sidecar_set_property "$file" "IPTC" "Caption" "$iptc_caption"
            set +x;;
        *.jpg )    
            jpeg_set_iptc "$file" "Headline" "$iptc_headline"
            jpeg_set_iptc "$file" "Caption" "$iptc_caption";;
    esac
}

echo "[INFO] Starting to watch $WATCH_DIR for new files..." >&2
inotifywait --monitor --recursive --quiet --event create --format %w%f $WATCH_DIR | while read new_file; do
    echo "[INFO] Received 'create' event for $new_file" >&2
    
    if is_output_file "$new_file" && is_variant "$new_file"; then
        # wait a bit so that the file has been fully written
        sleep 5
        fix_variantfile_iptc "$new_file"        
    fi
done
