#! /usr/bin/env bash

set -eu

declare -r APP_DIR=$(readlink -m "$HOME/.local/share/photo-scripts/")

export PATH="$(dirname $(readlink -f $0)):$APP_DIR:$PATH"

declare -r WATCH_DIR=$1

function kill_postsaveprocessor() {
    # FIXME use the lock file, contains the pid
    kill $POSTSAVEPROCESSOR_PID
}
trap kill_postsaveprocessor EXIT

echo "$(date) Starting RawTherapee with watched output directories" >> "$APP_DIR/rawtherapee.log"

postsaveprocessor "$WATCH_DIR" >> "$APP_DIR/rawtherapee_output_watcher.log" 2>&1 & 
declare -r POSTSAVEPROCESSOR_PID=$!


# NOTE script will wait until rawtherapee ends and then our EXIT trap will take care of cleaning up (incl. killing
# the watcher)
rawtherapee >> "$APP_DIR/rawtherapee.log" 2>&1